version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inquisitor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # İlerleyen safhalarda frontend ve backend servisleri buraya eklenecektir.

volumes:
  pgdata:
