export interface InteriorHotspot {
  id: string;
  x: number; // Yüzde olarak yatay konum (0 - 100)
  y: number; // Yüzde olarak dikey konum (0 - 100)
  title: string;
  category: 'npc' | 'clue' | 'atmosphere' | 'passage';
  icon: string;
  summary: string;
  description: string;
  clueSnippet?: string;
  actionText?: string;
  actionHref?: string;
}

export interface LocationInteriorData {
  id: string;
  // Mekân seçim menüsünde görünen kısa ad
  menuLabel: string;
  name: string;
  subtitle: string;
  scenarioType: string;
  npcId?: string;
  npcName?: string;
  backgroundImage: string;
  particleType: 'embers' | 'dust' | 'fog' | 'rain' | 'snow';
  // neon: meşale yerine pembe-camgöbeği titreyen neon ışığı (cyberpunk)
  lightingTone: 'warm-fire' | 'cold-moon' | 'dim-amber' | 'eerie-green' | 'neon';
  initialPan?: number; // Başlangıç kamera açısı (geriye dönük uyumluluk için tutuluyor)
  hotspots: InteriorHotspot[];
}

// İç mekânlar evrene göre ayrılır: aynı mekân id'si (ör. tavern) her evrende başka bir yerdir
const MEDIEVAL_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🍺 Taverna (Kardeş Aldric)',
    name: 'Ashenmoor Tavernası',
    subtitle: 'Karga ve Kadeh — Sırların ve Fısıltıların Sığınağı',
    scenarioType: 'medieval',
    npcId: 'tavern',
    npcName: 'Kardeş Aldric',
    backgroundImage: '/backgrounds/interior_medieval_tavern.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'aldric',
        x: 21,
        y: 55,
        title: 'Kardeş Aldric (Hancı)',
        category: 'npc',
        icon: '🍺',
        summary: 'Tezgâhın arkasında gergin bir şekilde kupa dolduran hancı.',
        description:
          'Kardeş Aldric, elleri hafifçe titreyerek müşterilerine bira dolduruyor. Bakışları sürekli kapıya ve şöminenin karanlık köşelerine kayıyor. Köydeki son olaylar hakkında bildiklerini saklamakta zorlanıyor gibi.',
        actionText: 'Aldric ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'barrels',
        x: 14,
        y: 62,
        title: 'Meşe Fıçılar ve Tezgâh Arkası',
        category: 'clue',
        icon: '🛢️',
        summary: 'Tezgâhın kenarına istiflenmiş eski meşe bira fıçıları.',
        description:
          'Fıçıların üzerinde kilise mührüne benzeyen kazınmış işaretler var. Varillerin arkasındaki zemini aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'fireplace',
        x: 86,
        y: 62,
        title: 'Büyük Taş Şömine',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Ateşin sıcaklığına sığınmış kapüşonlu köylüler ve çıtırdayan kütükler.',
        description:
          'Közlerin çıtırtısı arasında fısıltılar duyuluyor: "...dün gece mezarlık tarafında parlayan meşaleler vardı... Silas yine kilisenin çanını çalmadı..." Köylüler Engizitörün gölgesini görünce aniden susuyor.',
      },
      {
        id: 'table',
        x: 63,
        y: 60,
        title: 'Ortadaki Masalar ve Fısıldaşanlar',
        category: 'atmosphere',
        icon: '📜',
        summary: 'Karanlık köşede toplanmış tedirgin köy ahalisi.',
        description:
          'Masada devrilmiş bir kalay kupa ve üzerinde kırmızı balmumu lekeleri olan parşömen kırıntıları dikkat çekiyor.',
      },
      {
        id: 'stairs',
        x: 50,
        y: 46,
        title: 'Görkemli Çift Kanatlı Ahşap Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Karanlık kiralık odalara çıkan ahşap merdivenler.',
        description:
          'Yukarıdan ağır ayak sesleri ve tahta gıcırtıları geliyor. Hancının dediğine göre üst kattaki köşe oda iki gündür kilitli tutuluyor.',
      },
      {
        id: 'chandelier',
        x: 50,
        y: 16,
        title: 'Döküm Demir Avize',
        category: 'atmosphere',
        icon: '🕯️',
        summary: 'Yüksek ahşap kirişlerden sarkan ve damlayan balmumu mumları.',
        description:
          'İsli kirişlerden sarkan demir avize, salona titrek ve sıcak bir ışık yayıyor.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '⛪ Kilise (Peder Malachar)',
    name: 'Ashenmoor Kilisesi',
    subtitle: 'Aziz Jude Bazilikası — Taş Sütunlar ve Soğuk Dualar',
    scenarioType: 'medieval',
    npcId: 'church',
    npcName: 'Peder Malachar',
    backgroundImage: '/backgrounds/interior_medieval_church.webp',
    particleType: 'dust',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'malachar',
        x: 26,
        y: 68,
        title: 'Peder Malachar (Kürsü Yanındaki Din Adamı)',
        category: 'npc',
        icon: '⛪',
        summary: 'Oymalı vaaz kürsüsünün yanında soğuk bakışlarla bekleyen rahip.',
        description:
          'Peder Malachar dik ve kibirli duruşuyla seni süzüyor. Göğsündeki gümüş haç ve siyah cübbesiyle köyün ruhani otoritesini temsil ediyor; ancak gözlerindeki tedirginlik gizlenemiyor.',
        actionText: 'Malachar ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'pulpit',
        x: 20,
        y: 42,
        title: 'Oymalı Ahşap Vaaz Kürsüsü',
        category: 'atmosphere',
        icon: '📖',
        summary: 'Yüksek helezonik ahşap basamaklar ve süslü tavan gölgeliği.',
        description:
          'Pederin cemaate vaaz verdiği bu yüksek kürsünün basamaklarında yakın zamanda dökülmüş balmumu damlaları var.',
      },
      {
        id: 'altar',
        x: 50,
        y: 66,
        title: 'Kutsal Sunak ve Ayin Masası',
        category: 'atmosphere',
        icon: '🕯️',
        summary: 'Merkezi koridorun ucundaki mermer sunak ve şamdanlar.',
        description:
          'Sunağın üzerindeki mumların titrek aydınlığında mermer üzerindeki koyu renkli lekeler dikkat çekiyor.',
      },
      {
        id: 'tapestry',
        x: 82,
        y: 38,
        title: 'Gotik Duvar Halısı ve Gizli Duvar Nişi',
        category: 'clue',
        icon: '🗝️',
        summary: 'Sağ duvardaki antik dini halı ve arkasındaki kilitli emanet oyuğu.',
        description:
          'Halının arkasındaki taş oyukta eski el yazmaları ve mühürlü bir kutu var. Burayı aramak için resmi bir arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'rose_window',
        x: 50,
        y: 42,
        title: 'Devasa Gül Vitray Pencere',
        category: 'atmosphere',
        icon: '✨',
        summary: 'Ay ışığını süzerek kiliseyi aydınlatan muazzam vitray.',
        description:
          'Gül pencereden giren solgun ay ışığı toz zerrelerini aydınlatıyor ve taş zemine gotik renkli gölgeler düşürüyor.',
      },
      {
        id: 'candelabra',
        x: 91,
        y: 58,
        title: 'Döküm Demir Ayaklı Şamdan Grubu',
        category: 'atmosphere',
        icon: '🕯️',
        summary: 'Eriyen onlarca balmumu mumunun aydınlattığı sağ nef.',
        description:
          'Ağır balmumu ve tütsü kokusu kilisenin soğuk rutubetine karışıyor.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⚙️ Değirmen (Giles)',
    name: 'Ashenmoor Değirmeni',
    subtitle: 'Eski Un Değirmeni — Gıcırdayan Çarklar ve Beyaz Tozlar',
    scenarioType: 'medieval',
    npcId: 'mill',
    npcName: 'Değirmenci Giles',
    backgroundImage: '/backgrounds/interior_medieval_mill.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    initialPan: 0,
    hotspots: [
      {
        id: 'giles',
        x: 76,
        y: 58,
        title: 'Değirmenci Giles (Masa Başı)',
        category: 'npc',
        icon: '⚙️',
        summary: 'Unlu kıyafetleri ve düşünceli haliyle masasının başında duran değirmenci.',
        description:
          'Giles, un tozlarına bulanmış kıyafetleri ve şüpheci bakışlarıyla çalışma masasının başında duruyor. Değirmene gelenlerin kayıtlarını ve un çuvallarının nereye gittiğini en iyi o biliyor.',
        actionText: 'Giles ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'worktable',
        x: 84,
        y: 70,
        title: 'Hesap Masası ve Fener',
        category: 'clue',
        icon: '⚖️',
        summary: 'Sıcak sarı fener ışığında duran defter ve kilitli çekmece.',
        description:
          'Tezgâhın çekmecesinde un tozuyla kaplanmış şüpheli notlar ve mühürlü belgeler bulunuyor. Burayı detaylı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'gears',
        x: 11,
        y: 62,
        title: 'Devasa Ahşap Dişli Mekanizması',
        category: 'atmosphere',
        icon: '⚙️',
        summary: 'Değirmenin kalbi olan ağır meşe dişliler ve miller.',
        description:
          'Büyük ahşap dişliler her dönüşte gıcırdıyor. Çarkların arasına sıkışmış koyu renkli bir kumaş parçası rüzgârla dalgalanıyor.',
      },
      {
        id: 'grindstone',
        x: 25,
        y: 62,
        title: 'Büyük Değirmen Taşı ve Hazne',
        category: 'atmosphere',
        icon: '🪨',
        summary: 'Tahılı un haline getiren dairesel devasa öğütme mekanizması.',
        description:
          'Ağır taş haznenin etrafında taze öğütülmüş un dumanı tütüyor. Taşın kenarında koyu renkli, şüpheli sürtünme izleri var.',
      },
      {
        id: 'stairs',
        x: 50,
        y: 52,
        title: 'Tavan Arası Merdiveni',
        category: 'passage',
        icon: '🪜',
        summary: 'Yukarıdaki asma tahıl ambarına çıkan ahşap merdiven.',
        description:
          'Güneş ışınlarının süzüldüğü ahşap çatı aralığına ve tahıl ambarına çıkan basamaklar.',
      },
      {
        id: 'marked_sacks',
        x: 93,
        y: 82,
        title: 'İstiflenmiş Un Çuvalları',
        category: 'atmosphere',
        icon: '🌾',
        summary: 'Duvar dibine dizilmiş kenevir çuvallar.',
        description:
          'Çuvalların bazılarının üzerinde köy ambarının resmi damgası yerine tuhaf kırmızı işaretler çizilmiş.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🪦 Mezarlık (İhtiyar Silas)',
    name: 'Ashenmoor Mezarlığı',
    subtitle: 'Sisli Kabirler — Sessizliğin ve Toprağın Şahitliği',
    scenarioType: 'medieval',
    npcId: 'graveyard',
    npcName: 'İhtiyar Silas',
    backgroundImage: '/backgrounds/interior_medieval_graveyard.webp',
    particleType: 'fog',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'silas',
        x: 21,
        y: 54,
        title: 'İhtiyar Silas (Mezarcı)',
        category: 'npc',
        icon: '🪦',
        summary: 'Küreğine yaslanmış, çürük peleriniyle sisler içinde bekleyen ihtiyar.',
        description:
          'Silas, kırk yıldır bu mezarlıkta kazdığı çukurların başında duruyor. Yüzündeki derin kırışıklıklar ve çökük gözleri, canlılardan çok ölülerle konuştuğunu hissettiriyor.',
        actionText: 'Silas ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'lantern',
        x: 32,
        y: 80,
        title: 'Mezar Başındaki Gaz Lambası',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Yosunlu taşın dibinde sarı ışık saçan yağ feneri.',
        description:
          'Fenerin titrek alevi yoğun yer sisini yarıp geçmeye çalışıyor.',
      },
      {
        id: 'mausoleum',
        x: 84,
        y: 44,
        title: 'Antik Aile Anıt Mezarı',
        category: 'atmosphere',
        icon: '🏛️',
        summary: 'Gargoyle heykelleriyle süslü gotik taş türbe.',
        description:
          'Yosun tutmuş taş türbenin tepesindeki gargoyle heykelleri mezarlığa tepeden bakıyor.',
      },
      {
        id: 'crypt_search',
        x: 78,
        y: 60,
        title: 'Türbenin Parmaklıklı Demir Kapısı',
        category: 'clue',
        icon: '🗝️',
        summary: 'Zincirle sarılmış ancak kilidi kurcalanmış kapı.',
        description:
          'Türbenin demir parmaklıklarındaki zincir gevşetilmiş; içeride son günlerde yakılmış balmumu kalıntıları var. Burayı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'dead_trees',
        x: 48,
        y: 60,
        title: 'Sisli Kabir Yolu ve Çarpık Taşlar',
        category: 'atmosphere',
        icon: '🌫️',
        summary: 'Dolunayın altında uzanan soğuk mezar taşları ve sisli patika.',
        description:
          'Sıra sıra dizilmiş eski taş haçlar arasında hafif bir rüzgâr uğulduyor.',
      },
      {
        id: 'open_grave',
        x: 82,
        y: 84,
        title: 'Yosunlu Antik Lahit Kapağı',
        category: 'atmosphere',
        icon: '⛏️',
        summary: 'Ön plandaki çatlamış taş lahit.',
        description:
          'Lahit taşının kenarında kazınmış esrarengiz Latince mısralar görülüyor.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🌾 Çiftlik (Çiftçi Edmund)',
    name: 'Ashenmoor Çiftliği',
    subtitle: 'Köy Dışındaki Yalnız Araziler — Saman Kokusu ve Tedirgin Bakışlar',
    scenarioType: 'medieval',
    npcId: 'farm',
    npcName: 'Çiftçi Edmund',
    backgroundImage: '/backgrounds/interior_medieval_farm.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    initialPan: 0,
    hotspots: [
      {
        id: 'edmund',
        x: 85,
        y: 62,
        title: 'Çiftçi Edmund (Tırpanlı Çiftçi)',
        category: 'npc',
        icon: '🌾',
        summary: 'Elindeki tırpanı sıkıca tutarak savunmacı bir tavırla duran köylü.',
        description:
          'Çiftçi Edmund, nasırlı elleri ve çamurlu giysileriyle saman balyalarının önünde duruyor. Gözlerindeki güvensizlik ve korku açıkça hissediliyor; toprağını ve sırlarını korumaya kararlı görünüyor.',
        actionText: 'Edmund ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'hay_bales',
        x: 73,
        y: 76,
        title: 'İstiflenmiş Saman Balyaları',
        category: 'atmosphere',
        icon: '🌾',
        summary: 'Edmund’un yanında yükselen kuru saman yığınları.',
        description:
          'Kuru saman kokusu ahırın rutubetine karışıyor. Balyaların arkasındaki loşlukta saklanan biri kolayca gizlenebilir.',
      },
      {
        id: 'tools',
        x: 10,
        y: 46,
        title: 'Duvara Asılı Paslı Tırpanlar ve Oraklar',
        category: 'atmosphere',
        icon: '⛏️',
        summary: 'Taş duvara dizilmiş keskin tarım aletleri.',
        description:
          'Tırpanların birinin ucunda kurumuş koyu renkli bir leke var; pas mı yoksa kan mı olduğunu ayırt etmek güç.',
      },
      {
        id: 'secret_chest',
        x: 16,
        y: 76,
        title: 'Ahşap Sandık ve Fıçılar',
        category: 'clue',
        icon: '📦',
        summary: 'Sol taraftaki varillerin yanına bırakılmış kilitli oyma sandık.',
        description:
          'Sandığın üzerinde taze tebeşir tozu ve şüpheli mühürler bulunuyor. Burayı detaylı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'timber_roof',
        x: 60,
        y: 33,
        title: 'Asılı Yağ Feneri ve Çatı Kirişleri',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Ahşap kirişe asılı sıcak sarı fener.',
        description:
          'Fenerin ışığında havada süzülen saman tozları ve örümcek ağları parıldıyor.',
      },
      {
        id: 'hayloft',
        x: 44,
        y: 52,
        title: 'Arka Samanlık ve Ahşap Merdivenler',
        category: 'passage',
        icon: '🪜',
        summary: 'Ahırın derinliğindeki asma samanlık bölmesi.',
        description:
          'İçerideki gölgeli samanlık bölmesine uzanan ahşap merdivenler.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🩸 Revir (Doktor Harland)',
    name: 'Ashenmoor Şifahanesi',
    subtitle: 'Taş Duvarlar Arasında Şifa ve Sır — İksir Şişeleri ve Neşterler',
    scenarioType: 'medieval',
    npcId: 'clinic',
    npcName: 'Doktor Harland',
    backgroundImage: '/backgrounds/interior_medieval_clinic.webp',
    particleType: 'fog',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'harland',
        x: 78,
        y: 56,
        title: 'Doktor Harland (Köy Hekimi)',
        category: 'npc',
        icon: '🩺',
        summary: 'Hassas terazi ve iksir şişelerinin başında soğukkanlılıkla duran hekim.',
        description:
          'Doktor Harland, siyah hekim cübbesi ve dikkatli bakışlarıyla ilaç şişelerini düzenliyor. Köydeki hastalıkları, zehirleri ve son ölümlerin ardındaki gerçek anatomik sebepleri herkesten iyi bildiği şüphesiz.',
        actionText: 'Harland ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'apothecary_table',
        x: 68,
        y: 72,
        title: 'Hekim Tezgâhı ve İlaç Şişeleri',
        category: 'clue',
        icon: '🧪',
        summary: 'Havanlar, terazi, açık tıp defteri ve cerrahi aletler.',
        description:
          'Tezgâhta üzerinde isim yazılı olmayan koyu renkli bir zehir şişesi ve gizli bir otopsi kaydı duruyor. Burayı detaylı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'shelves',
        x: 92,
        y: 50,
        title: 'Ecza Dolapları ve Cam Kavanozlar',
        category: 'atmosphere',
        icon: '🏺',
        summary: 'Sıra sıra dizilmiş tentürler, iksirler ve tozlar.',
        description:
          'Ahşap raflarda köydeki her türlü hastalığa ve belki de ölümcül zehirlere ait kavanozlar bulunuyor.',
      },
      {
        id: 'exam_cot',
        x: 22,
        y: 76,
        title: 'Eski Deri Muayene Masası',
        category: 'atmosphere',
        icon: '🛏️',
        summary: 'Gotik taş pencerenin altına yerleştirilmiş sedir.',
        description:
          'Köyde yaralananların ve son nefesini verenlerin yattığı bu sedirde solgun ay ışığı parıldıyor.',
      },
      {
        id: 'fireplace',
        x: 50,
        y: 58,
        title: 'Taş Ocak ve Közler',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'İlaçların kaynatıldığı taş ocak ve közler.',
        description:
          'Taş ocağın kor ateşi soğuk odaya hafif bir sıcaklık veriyor.',
      },
      {
        id: 'herbs',
        x: 45,
        y: 22,
        title: 'Tavandan Sarkan Kurutulmuş Şifalı Otlar',
        category: 'atmosphere',
        icon: '🌿',
        summary: 'İplerle asılmış lavanta, adamotu ve sarmaşıklar.',
        description:
          'Kurutulmuş otların keskin ve acı kokusu tüm odayı kaplıyor.',
      },
    ],
  },
};

// Neon Prime (cyberpunk). "Aranabilecek yer" noktaları sabit bir ipucu vermez: oyuncuyu mekânın
// aramasına yönlendirir, bulunan ipucu o vaka için üretilmiş gerçek ipucudur.
const CYBERPUNK_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🚔 Karakol (Kael Voss)',
    name: 'Neon Prime Karakolu',
    subtitle: 'Nöbetçi Masası — Arama İzinlerinin ve Bitmeyen Raporların Yeri',
    scenarioType: 'cyberpunk',
    npcId: 'tavern',
    npcName: 'Kael Voss',
    backgroundImage: '/backgrounds/interior_cyberpunk_tavern.webp',
    particleType: 'rain',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'kael',
        x: 33,
        y: 57,
        title: 'Memur Kael Voss (Nöbetçi Masası)',
        category: 'npc',
        icon: '👮',
        summary: 'Holografik dosyaların başında yorgun gözlerle bekleyen memur.',
        description:
          'Kael Voss, gözündeki implantın soluk ışığında ekrandaki dosyaları kaydırıyor. Her isteği masasına ne kadar iş açacağına göre tartıyor. Arama izinleri onun imzasından geçiyor.',
        actionText: 'Kael Voss ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'wanted_board',
        x: 9,
        y: 38,
        title: 'Aranan Afişleri ve Şehir Haritası',
        category: 'atmosphere',
        icon: '📌',
        summary: 'Solmuş afişler, işaretli bir harita ve üst üste yapıştırılmış notlar.',
        description:
          'Mantar panoda solmuş aranan afişleri, raptiyelerle işaretlenmiş bir şehir haritası ve üst üste yapıştırılmış notlar var. Bazı dosyalar çoktan kapanmış ama kimse afişleri indirmeye zahmet etmemiş.',
      },
      {
        id: 'holding_cell',
        x: 51,
        y: 52,
        title: 'Nezarethane',
        category: 'atmosphere',
        icon: '🔒',
        summary: 'Soluk camgöbeği ışık altında parmaklıkların ardındaki gözaltılar.',
        description:
          'Parmaklıkların ardında gözaltılar bekliyor. Kapının önündeki iki memur alçak sesle konuşuyor; içeriden biri dışarıdakilere bir şey fısıldamaya çalışıyor.',
      },
      {
        id: 'evidence_lockers',
        x: 64,
        y: 55,
        title: 'Delil Dolapları',
        category: 'clue',
        icon: '🗄️',
        summary: 'Sıra sıra dizilmiş numaralı metal dolaplar.',
        description:
          'Numaralı metal dolapların birkaçının kilidi zorlanmış gibi duruyor. Karakolun burasını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'street_window',
        x: 85,
        y: 47,
        title: 'Yağmurlu Cadde',
        category: 'atmosphere',
        icon: '🌃',
        summary: 'Camın ardında neon tabelalar ve seyyar yemek tezgâhları.',
        description:
          'Neon tabelalar, seyyar yemek tezgâhları ve alçaktan uçan bir dron. Şehir, karakolun içinde olanlardan habersiz akıp gidiyor.',
      },
      {
        id: 'printer',
        x: 26,
        y: 88,
        title: 'Eski Yazıcı',
        category: 'atmosphere',
        icon: '🖨️',
        summary: 'Hâlâ kâğıtla çalışan, son çıktısı yarım kalmış bir yazıcı.',
        description:
          'Karakol yeni sistemlere geçmeyi yıllardır erteliyor. Yazıcının ağzında yarım kalmış bir rapor sallanıyor.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🍜 Lokanta (Mirel Sato)',
    name: 'Static Spoon',
    subtitle: 'Gece Boyu Açık Erişte Lokantası — Kuryelerin, Polislerin ve Uykusuzların Durağı',
    scenarioType: 'cyberpunk',
    npcId: 'church',
    npcName: 'Mirel Sato',
    backgroundImage: '/backgrounds/interior_cyberpunk_church.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'mirel',
        x: 18,
        y: 50,
        title: 'Mirel Sato (Tezgâh)',
        category: 'npc',
        icon: '🍜',
        summary: 'Buharın içinde kepçesiyle kazanların başında duran lokanta sahibi.',
        description:
          'Metal önkolu buharın içinde parlıyor. Kepçeyi kazana daldırırken gözü kapıdan girip çıkan herkeste. Bu tezgâhtan geçen her söz bir gün işine yarayabilir.',
        actionText: 'Mirel Sato ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'regulars',
        x: 44,
        y: 60,
        title: 'Tezgâhtaki Müdavimler',
        category: 'atmosphere',
        icon: '🥢',
        summary: 'Eriştelerine eğilmiş kuryeler ve gece vardiyasından çıkanlar.',
        description:
          'Konuşmalar alçak sesle yapılıyor ama yan yana oturanlar birbirinin her kelimesini duyuyor. Burada sır tutmak, erişteyi soğumadan bitirmekten zor.',
      },
      {
        id: 'kitchen_door',
        x: 53,
        y: 50,
        title: 'Mutfağa Açılan Arka Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'Aralık kapının ardında tavalar ve sokağa açılan servis çıkışı.',
        description:
          'Mutfağın arkasındaki servis çıkışı doğrudan ara sokağa açılıyor. Buradan girip çıkan birini tezgâhtakiler fark etmez.',
      },
      {
        id: 'vending_machine',
        x: 65,
        y: 44,
        title: 'Ezik Otomat',
        category: 'atmosphere',
        icon: '🥤',
        summary: 'Camı çatlamış, yarısı boş bir içecek otomatı.',
        description:
          'Biri yumruğunu camına geçirmiş; çatlak hâlâ duruyor. İçindeki içeceklerin yarısının son kullanma tarihi çoktan geçmiş.',
      },
      {
        id: 'back_booth',
        x: 85,
        y: 80,
        title: 'Arka Köşedeki Masa',
        category: 'clue',
        icon: '🍲',
        summary: 'Yarım bırakılmış bir kâse ve dağılmış yemek çubukları.',
        description:
          'Biri buradan aceleyle kalkmış. Lokantanın arka köşelerini aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'foggy_window',
        x: 86,
        y: 33,
        title: 'Buğulu Vitrin',
        category: 'atmosphere',
        icon: '🌧️',
        summary: 'Yağmur damlalarının arasından süzülen pembe neon.',
        description:
          'Buğulu camın ardında caddenin neon ışıkları bulanıklaşıyor. İçeriden dışarısı görünmüyor, dışarıdan da içerisi.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🏥 Klinik (Brakk Coil)',
    name: 'Neon Prime Kliniği',
    subtitle: 'Yeraltı Siber Cerrahisi — Faturasız Ameliyatlar, Sorusuz Hastalar',
    scenarioType: 'cyberpunk',
    npcId: 'graveyard',
    npcName: 'Brakk Coil',
    backgroundImage: '/backgrounds/interior_cyberpunk_graveyard.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'brakk',
        x: 70,
        y: 57,
        title: 'Brakk Coil (Çalışma Masası)',
        category: 'npc',
        icon: '🩺',
        summary: 'Masasında mekanik bir eli söken siber cerrah.',
        description:
          'Brakk, başını kaldırmadan konuşuyor; tornavidası mekanik elin eklemlerinde dolaşıyor. Burada her işlemin bir bedeli var ve Brakk kimseye güvenmiyor.',
        actionText: 'Brakk Coil ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'bio_storage',
        x: 21,
        y: 48,
        title: 'Biyolojik Saklama Dolapları',
        category: 'clue',
        icon: '🧪',
        summary: 'Buzlu camların ardında yeşil ışıkta parlayan şişeler.',
        description:
          'Etiketsiz tüpler ve şişeler raflara dizilmiş; bazı rafların yakın zamanda boşaltıldığı belli. Kliniği aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'surgery_chair',
        x: 56,
        y: 65,
        title: 'Ameliyat Koltuğu',
        category: 'atmosphere',
        icon: '💺',
        summary: 'Tavandan sarkan robotik kolların altındaki yıpranmış koltuk.',
        description:
          'Deri koltuk sayısız ameliyattan geçmiş. Zemindeki lekeler hiçbir zaman tam olarak temizlenmemiş.',
      },
      {
        id: 'plastic_curtain',
        x: 33,
        y: 45,
        title: 'Plastik Perdenin Ardı',
        category: 'passage',
        icon: '🚪',
        summary: 'Kutularla dolu bir arka odayı gizleyen yarı saydam perde.',
        description:
          'Perdenin ardındaki odada hastaların görmemesi gereken işler yapılıyor olmalı. İçeriden soğutucu uğultusu geliyor.',
      },
      {
        id: 'scrap_implants',
        x: 91,
        y: 86,
        title: 'Hurda İmplantlar',
        category: 'atmosphere',
        icon: '🦾',
        summary: 'Bir kasaya gelişigüzel atılmış sökülmüş robot kolları.',
        description:
          'Kullanılmış implantlar ve sökülmüş protezler üst üste yığılmış. Kimin bedeninden çıktıkları belli değil.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '🛠️ Tamirhane (AURA-9)',
    name: 'AURA Tamirhanesi',
    subtitle: 'Siber Protez ve Robot Atölyesi — Kıvılcımlar, Lehim ve Yedek Parçalar',
    scenarioType: 'cyberpunk',
    npcId: 'mill',
    npcName: 'AURA-9',
    backgroundImage: '/backgrounds/interior_cyberpunk_mill.webp',
    particleType: 'embers',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'aura',
        x: 37,
        y: 51,
        title: 'AURA-9 (Lehim Tezgâhı)',
        category: 'npc',
        icon: '🤖',
        summary: 'Bir devre kartını lehimleyen beyaz-krom kabuklu android.',
        description:
          'AURA-9’un mavi optik sensörleri her hareketi kaydediyor. Ses tonu kibar ve ticari, ama bakışları bir makineye göre fazlasıyla dikkatli.',
        actionText: 'AURA-9 ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'robot_arm',
        x: 17,
        y: 62,
        title: 'Robotik Montaj Kolu',
        category: 'atmosphere',
        icon: '🦿',
        summary: 'Masanın üzerinde kendi kendine çalışan montaj kolu.',
        description:
          'Kol, sahibine ihtiyaç duymadan vida sıkıyor. Atölyede kimse yokken de iş durmuyor.',
      },
      {
        id: 'limb_rack',
        x: 55,
        y: 42,
        title: 'Yedek Uzuv Rafı',
        category: 'atmosphere',
        icon: '🦾',
        summary: 'Kancalara asılı kollar ve raflarda dizili boş bakışlı yüzler.',
        description:
          'Bazı parçaların seri numaraları kazınarak silinmiş. Bu rafın kaçta kaçının yasal yoldan geldiğini kimse sormuyor.',
      },
      {
        id: 'circuit_table',
        x: 45,
        y: 88,
        title: 'Devre Kartı Masası',
        category: 'clue',
        icon: '💾',
        summary: 'Yarı sökülmüş kartlar ve hafıza modülleri.',
        description:
          'Masadaki hafıza modüllerinden birinin kayıtları silinmeye çalışılmış gibi. Atölyeyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'shutter',
        x: 82,
        y: 52,
        title: 'Yarı Açık Kepenk',
        category: 'passage',
        icon: '🚪',
        summary: 'Kepengin altından görünen yağmurlu sokak.',
        description:
          'Atölyeye gece yarısı da girip çıkılabiliyor. Kepengin önündeki ıslak zeminde silik ayak izleri var.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🏮 Sokak Pazarı (Ash)',
    name: 'Gece Pazarı',
    subtitle: 'Neon Prime Sokak Pazarı — Hurda Teknoloji, Sokak Yemeği ve Satılık Fısıltılar',
    scenarioType: 'cyberpunk',
    npcId: 'farm',
    npcName: 'Ash',
    backgroundImage: '/backgrounds/interior_cyberpunk_farm.webp',
    particleType: 'rain',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'ash',
        x: 21,
        y: 57,
        title: 'Ash (Hurda Tezgâhı)',
        category: 'npc',
        icon: '🧥',
        summary: 'Kapüşonunun altından kalabalığı izleyen sokak satıcısı.',
        description:
          'Gözlüğü alnında, eldivenli elleri kenetli. Bu pazarda görünmez olmak bir zırh; Ash de bu zırhın ardından her şeyi görüyor.',
        actionText: 'Ash ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'ash_stall',
        x: 35,
        y: 85,
        title: 'Ash’in Tezgâhı',
        category: 'clue',
        icon: '🔌',
        summary: 'Kablo yumakları, eski piller ve elden düşme devre kartları.',
        description:
          'Tezgâhtaki parçaların bazıları bir hurdaya göre fazla yeni duruyor. Tezgâhı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'wok_stall',
        x: 44,
        y: 59,
        title: 'Buharlı Wok Tezgâhı',
        category: 'atmosphere',
        icon: '🥘',
        summary: 'Devasa tavada erişte çeviren bir aşçı.',
        description:
          'Buhar neon ışıkla karışıyor; kızgın yağın sesi yakındaki konuşmaları bastırıyor.',
      },
      {
        id: 'lantern_alley',
        x: 65,
        y: 46,
        title: 'Fenerli Pazar Sokağı',
        category: 'passage',
        icon: '🏮',
        summary: 'Kâğıt fenerlerin altında ilerleyen şemsiyeli kalabalık.',
        description:
          'Bu kalabalığın içinde biri takip edilse kimse fark etmez. Sokak, şehrin daha karanlık katlarına doğru uzanıyor.',
      },
      {
        id: 'hanging_cables',
        x: 85,
        y: 40,
        title: 'Karşı Tezgâh',
        category: 'atmosphere',
        icon: '🧵',
        summary: 'Kancalardan sarkan kablolar ve tencereler.',
        description:
          'Satıcı müşterilerden çok sokağın başını izliyor. Polis geldiğinde bu tezgâhın ilk kapanan olacağı belli.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🍸 Bar (Vera Nyx)',
    name: 'Velvet Static',
    subtitle: 'Karartma Barı — Paralı Askerlerin, Aracıların ve Kaybolmak İsteyenlerin Mekânı',
    scenarioType: 'cyberpunk',
    npcId: 'clinic',
    npcName: 'Vera Nyx',
    backgroundImage: '/backgrounds/interior_cyberpunk_clinic.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'vera',
        x: 72,
        y: 48,
        title: 'Vera Nyx (Bar Tezgâhı)',
        category: 'npc',
        icon: '🍸',
        summary: 'Bir bardağı ağır ağır parlatırken salonu süzen barmen.',
        description:
          'Çene hattındaki implant neon ışıkta belli belirsiz parlıyor. Herkesle samimi konuşuyor ama kendisi hakkında hiçbir şey söylemiyor.',
        actionText: 'Vera Nyx ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'private_room',
        x: 28,
        y: 45,
        title: 'Boncuk Perdeli Özel Oda',
        category: 'passage',
        icon: '🚪',
        summary: 'Kırmızı ışıklı, alçak sesle pazarlık yapılan arka oda.',
        description:
          'Perdenin ardında birileri anlaşma yapıyor. Davetsiz girenlerin buradan nasıl çıktığını kimse hatırlamıyor.',
      },
      {
        id: 'stage',
        x: 50,
        y: 45,
        title: 'Sahne',
        category: 'atmosphere',
        icon: '🎸',
        summary: 'Sis makinesinin dumanında çalan bir grup.',
        description:
          'Müzik o kadar yüksek ki masalardaki fısıltılar kayboluyor. Burada konuşulanı ancak yan masadaki duyar.',
      },
      {
        id: 'side_booth',
        x: 9,
        y: 64,
        title: 'Yan Odadaki Masa',
        category: 'atmosphere',
        icon: '🤝',
        summary: 'Grafitili duvarın önünde pazarlık yapan iki kişi.',
        description:
          'Siber kollu iki kişi masaya eğilmiş, bir şeyin fiyatında anlaşmaya çalışıyor. Seni görünce sesleri kısılıyor.',
      },
      {
        id: 'behind_bar',
        x: 80,
        y: 72,
        title: 'Bar Tezgâhının Arkası',
        category: 'clue',
        icon: '🍾',
        summary: 'Işıklı raflar ve tezgâhın altındaki kilitli çekmeceler.',
        description:
          'Rafların arkasında içkiden fazlası saklanıyor olabilir. Barın arkasını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
    ],
  },
};

// Jinling (Çin hanedan dönemi). Cyberpunk'taki gibi "aranabilecek yer" noktaları sabit ipucu vermez,
// oyuncuyu mekânın aramasına yönlendirir.
const CHINA_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🍵 Çay Evi (Lin Feng)',
    name: 'Altın Lotus Çay Evi',
    subtitle: 'Çay Evi ve Han — Yolcuların, Tüccarların ve Fısıltıların Durağı',
    scenarioType: 'china',
    npcId: 'tavern',
    npcName: 'Lin Feng',
    backgroundImage: '/backgrounds/interior_china_tavern.webp',
    particleType: 'dust',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'lin_feng',
        x: 19,
        y: 49,
        title: 'Lin Feng (Çay Tezgâhı)',
        category: 'npc',
        icon: '🍵',
        summary: 'Demliği havada tutup çayı uzun bir yayla bardağa döken çay ustası.',
        description:
          'Lin Feng kibarca gülümsüyor ama gözleri her masada. Burada konuşulan her sözün bir değeri olduğunu ve o değeri kimin ödeyeceğini çok iyi biliyor.',
        actionText: 'Lin Feng ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'tea_counter',
        x: 30,
        y: 71,
        title: 'Çay Tezgâhı',
        category: 'atmosphere',
        icon: '🫖',
        summary: 'Demlikler, porselen fincanlar ve sıra sıra çay kavanozları.',
        description:
          'Kavanozların her birinde başka bir yörenin çayı var. En pahalıları, tezgâhın arkasında kilitli bir dolapta duruyor.',
      },
      {
        id: 'upper_gallery',
        x: 49,
        y: 27,
        title: 'Üst Kattaki Localar',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Perdeli, kafes paravanlı özel localar.',
        description:
          'Memurlar ve zengin tüccarlar üst katta, perdelerin ardında oturuyor. Aşağıdan bakan biri yalnızca gölgelerini görebilir.',
      },
      {
        id: 'guests',
        x: 60,
        y: 66,
        title: 'Fısıldaşan Müşteriler',
        category: 'atmosphere',
        icon: '🗣️',
        summary: 'Mangalın başında alçak sesle konuşan yolcular.',
        description:
          'Konuşmalar sen yaklaşınca kesiliyor. Masadakilerden biri fincanını bırakıp bakışlarını kapıya çeviriyor.',
      },
      {
        id: 'staircase',
        x: 75,
        y: 51,
        title: 'Üst Kata Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Oymalı tırabzanlı ahşap merdiven.',
        description:
          'Merdivenin basamakları gıcırdıyor; yukarı çıkan herkesi aşağıdakiler duyuyor. Han odaları koridorun sonunda.',
      },
      {
        id: 'back_room',
        x: 92,
        y: 55,
        title: 'Arka Odanın Kapısı',
        category: 'clue',
        icon: '🚪',
        summary: 'Avluya açılan, yarı aralık sürgülü kapı.',
        description:
          'Lin Feng özel misafirlerini bu kapıdan arka odaya alıyor. Çay evini aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🏯 Karargâh (Komutan Zhao)',
    name: 'İmparatorluk Garnizonu',
    subtitle: 'Muhafız Karargâhı — Silahların, Mühürlerin ve Emirlerin Salonu',
    scenarioType: 'china',
    npcId: 'church',
    npcName: 'Komutan Zhao',
    backgroundImage: '/backgrounds/interior_china_church.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'zhao',
        x: 84.5,
        y: 57,
        title: 'Komutan Zhao (Harita Masası)',
        category: 'npc',
        icon: '🏯',
        summary: 'Zırhının içinde dimdik duran, yüzü yara izli komutan.',
        description:
          'Zhao düzensizliğe ve ihanete tahammül etmiyor. Sert bir sesle konuşuyor ve her sorunun askerlerinin onurunu lekeleyip lekelemeyeceğini tartıyor.',
        actionText: 'Komutan Zhao ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'map_table',
        x: 57.5,
        y: 81,
        title: 'Savaş Haritası Masası',
        category: 'clue',
        icon: '🗺️',
        summary: 'Açılmış bir harita, balmumu mühürler ve fırça takımı.',
        description:
          'Haritanın üzerinde devriye yollarını gösteren işaretler var; bazıları yakın zamanda değiştirilmiş. Karargâhı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'weapon_racks',
        x: 11,
        y: 39,
        title: 'Silah Rafları',
        category: 'atmosphere',
        icon: '🔱',
        summary: 'Mızraklar, teberler ve kılıçlarla dolu raflar.',
        description:
          'Rafların her biri numaralı. Garnizonun silahları sayılı; eksik olan bir tanesi bile komutanın gözünden kaçmaz.',
      },
      {
        id: 'armor_stand',
        x: 26.5,
        y: 59,
        title: 'Zırh Askısı',
        category: 'atmosphere',
        icon: '🛡️',
        summary: 'Kırmızı tüylü miğferiyle boş bir pul zırh.',
        description:
          'Zırh, savaşta ölen eski bir komutana ait. Askerler önünden geçerken başlarını eğiyor.',
      },
      {
        id: 'barracks_door',
        x: 62.5,
        y: 53,
        title: 'Kışlaya Açılan Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'İki muhafızın beklediği ağır ahşap kapı.',
        description:
          'Kapının ardındaki koridor kışlaya ve zindana iniyor. Muhafızlar komutanın izni olmadan kimseyi geçirmiyor.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '⛩️ Tapınak (Keşiş Huikang)',
    name: 'Kadim Dağ Tapınağı',
    subtitle: 'Ata Ruhlarının Salonu — Tütsü, Mum ve Sessizlik',
    scenarioType: 'china',
    npcId: 'graveyard',
    npcName: 'Keşiş Huikang',
    backgroundImage: '/backgrounds/interior_china_graveyard.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    initialPan: 0,
    hotspots: [
      {
        id: 'huikang',
        x: 17.5,
        y: 66,
        title: 'Keşiş Huikang (Tütsü Kazanı)',
        category: 'npc',
        icon: '⛩️',
        summary: 'Tespihini çeken, gözleri yarı kapalı yaşlı keşiş.',
        description:
          'Huikang sakin bir sesle, bilmece gibi konuşuyor. İnsanların dünyevi hırslarının altındaki niyetleri sezdiğini söylüyor.',
        actionText: 'Keşiş Huikang ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'spirit_tablets',
        x: 43.5,
        y: 55,
        title: 'Ata Ruhu Tabletleri',
        category: 'clue',
        icon: '🕯️',
        summary: 'Mumlarla çevrili, sıra sıra dizilmiş ahşap tabletler.',
        description:
          'Tabletlerden birinin önündeki mumlar diğerlerinden yeni. Tapınağı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'statue',
        x: 42.5,
        y: 37,
        title: 'Altın Heykel',
        category: 'atmosphere',
        icon: '🪷',
        summary: 'Arka nişte oturan, yaldızı dökülmüş heykel.',
        description:
          'Heykelin önündeki tütsü dumanı hiç dağılmıyor. Köylüler burada verilen sözlerin bozulmadığına inanıyor.',
      },
      {
        id: 'incense_burner',
        x: 52,
        y: 71,
        title: 'Bronz Tütsü Kazanı',
        category: 'atmosphere',
        icon: '🌫️',
        summary: 'Salonun ortasında duman tüten büyük kazan.',
        description:
          'Kazandaki küller henüz soğumamış. Biri gece yarısı burada uzun süre dua etmiş olmalı.',
      },
      {
        id: 'courtyard_doors',
        x: 87.5,
        y: 51,
        title: 'Avluya Açılan Kafes Kapılar',
        category: 'passage',
        icon: '🚪',
        summary: 'Oymalı, kafesli büyük ahşap kapılar.',
        description:
          'Kapılar ay ışığındaki avluya ve oradan dağ yoluna açılıyor. Gece tapınağa girip çıkan biri buradan geçmek zorunda.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⚒️ Demirci (Usta Guan)',
    name: 'Usta Guan’ın Demirci Ocağı',
    subtitle: 'Silah Atölyesi — Kor, Çelik ve Çekiç Sesleri',
    scenarioType: 'china',
    npcId: 'mill',
    npcName: 'Usta Guan',
    backgroundImage: '/backgrounds/interior_china_mill.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'guan',
        x: 36,
        y: 50,
        title: 'Usta Guan (Örs)',
        category: 'npc',
        icon: '⚒️',
        summary: 'Kızgın bir bıçağı dövmek için çekicini kaldırmış iri yarı demirci.',
        description:
          'Guan’ın sesi çekicinden daha gür. Bu mahalledeki her silahı tanıyor ve kılıçlarının onursuz bir iş için kullanıldığı imasına öfkeleniyor.',
        actionText: 'Usta Guan ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'furnace',
        x: 16.5,
        y: 54,
        title: 'Taş Ocak',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Kor dolu, körükle beslenen taş ocak.',
        description:
          'Ocak gece gündüz yanıyor. Atölyede çalışan çırak, körüğün başından hiç ayrılmıyor.',
      },
      {
        id: 'blade_rack',
        x: 55,
        y: 39,
        title: 'Bitmiş Kılıçların Rafı',
        category: 'clue',
        icon: '🗡️',
        summary: 'Duvara dizilmiş kılıçlar ve bıçaklar.',
        description:
          'Raftaki kılıçların arasında bir boşluk var. Atölyeyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'quench_buckets',
        x: 52.5,
        y: 83,
        title: 'Su Kovaları',
        category: 'atmosphere',
        icon: '🪣',
        summary: 'Kızgın çeliğin soğutulduğu, buhar tüten kovalar.',
        description:
          'Kovaların dibinde demir talaşı birikmiş. Su sık sık değiştirilmiyor.',
      },
      {
        id: 'ingot_shelves',
        x: 70,
        y: 47,
        title: 'Külçe Rafları',
        category: 'atmosphere',
        icon: '🧱',
        summary: 'Üst üste dizilmiş demir külçeler.',
        description:
          'Külçelerin bir kısmı garnizonun mührünü taşıyor. Guan, ordu için de silah dövüyor.',
      },
      {
        id: 'workshop_door',
        x: 85,
        y: 47,
        title: 'Sokağa Açılan Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'Fenerle aydınlanan çift kanatlı ağır kapı.',
        description:
          'Kapının sürgüsü içeriden çekiliyor. Gece atölyeye girmek isteyen birinin Guan’ı uyandırması gerekir.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🎣 İskele (Mei Teyze)',
    name: 'Nehir İskelesi',
    subtitle: 'Balıkçı İskelesi — Ağlar, Kayıklar ve Sisli Sular',
    scenarioType: 'china',
    npcId: 'farm',
    npcName: 'Mei Teyze',
    backgroundImage: '/backgrounds/interior_china_farm.webp',
    particleType: 'fog',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'mei',
        x: 23.5,
        y: 50,
        title: 'Mei Teyze (Ağ Başı)',
        category: 'npc',
        icon: '🎣',
        summary: 'Mangalın yanında ağ onaran yaşlı balıkçı kadın.',
        description:
          'Mei Teyze ağı onarırken yan gözle seni süzüyor. Nehir kıyısından geçen hiçbir şey gözünden kaçmaz, ama yabancılara saf görünmeyi iyi bilir.',
        actionText: 'Mei Teyze ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'fish_baskets',
        x: 40,
        y: 71,
        title: 'Balık Sepetleri',
        category: 'atmosphere',
        icon: '🐟',
        summary: 'Mangalın başında sıra sıra balık dolu sepetler.',
        description:
          'Sabah tutulan balıklar hâlâ satılmamış. Bugün pazara inen olmamış gibi.',
      },
      {
        id: 'nets',
        x: 27.5,
        y: 21,
        title: 'Kurumaya Asılmış Ağlar',
        category: 'atmosphere',
        icon: '🕸️',
        summary: 'Tavan kirişlerinden sarkan ıslak ağlar.',
        description:
          'Ağlardan biri yeni yırtılmış; düğümler aceleyle atılmış.',
      },
      {
        id: 'covered_pier',
        x: 57.5,
        y: 50,
        title: 'Üstü Kapalı İskele',
        category: 'passage',
        icon: '🌉',
        summary: 'Fenerlerle aydınlanan ahşap iskele yolu.',
        description:
          'İskele nehir boyunca mahallenin öbür ucuna uzanıyor. Gece buradan geçen birini sadece Mei Teyze görür.',
      },
      {
        id: 'moored_boats',
        x: 80,
        y: 66,
        title: 'Bağlı Kayıklar',
        category: 'clue',
        icon: '🛶',
        summary: 'İskeleye bağlanmış, halatları gevşek ahşap kayıklar.',
        description:
          'Kayıklardan birinin içi diğerlerinden ıslak; yakın zamanda kullanılmış. İskeleyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'far_pavilions',
        x: 87.5,
        y: 33,
        title: 'Karşı Kıyıdaki Köşkler',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Sisin ardında ışıkları yanan köşkler.',
        description:
          'Karşı kıyıda eğlence sürüyor. Nehrin sesi, oradaki müziği buraya kadar taşıyor.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🌿 Şifacı (Bilgin Song)',
    name: 'Saray Eczanesi',
    subtitle: 'Şifacı ve Baharatçı — Kökler, Otlar ve Gizli Formüller',
    scenarioType: 'china',
    npcId: 'clinic',
    npcName: 'Bilgin Song',
    backgroundImage: '/backgrounds/interior_china_clinic.webp',
    particleType: 'dust',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'song',
        x: 86,
        y: 55,
        title: 'Bilgin Song (Tezgâh)',
        category: 'npc',
        icon: '🌿',
        summary: 'Taş havanda ot döven, mavi cüppeli hekim.',
        description:
          'Song yumuşak ve ölçülü konuşuyor; duygulardan çok akla değer veriyor. İlaçlar kadar zehirleri de iyi tanıdığını gizlemiyor.',
        actionText: 'Bilgin Song ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'medicine_drawers',
        x: 43.5,
        y: 45,
        title: 'İlaç Çekmeceleri',
        category: 'clue',
        icon: '🗄️',
        summary: 'Duvarı baştan sona kaplayan yüzlerce küçük çekmece.',
        description:
          'Çekmecelerden birinin tozu silinmiş, kulpu parlıyor. Eczaneyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'back_room',
        x: 19,
        y: 61,
        title: 'Perdeli Arka Oda',
        category: 'passage',
        icon: '🚪',
        summary: 'Perdenin ardından sızan yeşil bir ışık.',
        description:
          'Arka odada bir şey kaynıyor. Song oraya müşterileri hiç almıyor.',
      },
      {
        id: 'acupuncture_model',
        x: 65.5,
        y: 53,
        title: 'Akupunktur Heykeli',
        category: 'atmosphere',
        icon: '🧍',
        summary: 'Vücudun noktalarını gösteren bronz insan figürü.',
        description:
          'Figürün boynundaki birkaç nokta, sık dokunulmaktan parlamış.',
      },
      {
        id: 'hanging_herbs',
        x: 35,
        y: 21,
        title: 'Asılı Kurutulmuş Otlar',
        category: 'atmosphere',
        icon: '🌾',
        summary: 'Tavandan sarkan kökler, otlar ve su kabakları.',
        description:
          'Otların bazıları buralarda yetişmiyor; uzak eyaletlerden getirilmiş, pahalı ve nadir.',
      },
    ],
  },
};

// Frosthold (kış). Açık hava sahnelerinde kar yağar; "aranabilecek yer" noktaları sabit ipucu vermez.
const WINTER_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🔥 Kış Hanı (Torstein)',
    name: 'Ocak Ateşi Hanı',
    subtitle: 'Kış Hanı — Fırtınadan Kaçanların Son Sığınağı',
    scenarioType: 'winter',
    npcId: 'tavern',
    npcName: 'Torstein',
    backgroundImage: '/backgrounds/interior_winter_tavern.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    hotspots: [
      {
        id: 'torstein',
        x: 33,
        y: 53,
        title: 'Torstein (Tezgâh)',
        category: 'npc',
        icon: '🔥',
        summary: 'Maşrapalara sıcak bira dolduran iri yarı, örgü sakallı hancı.',
        description:
          'Torstein müşterilerini kollar ve kimin fırtınadan önce geçidi aştığını bilir. Ocağın başında konuşulanları duyar ama duyduklarını kolay kolay anlatmaz.',
        actionText: 'Torstein ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'hearth',
        x: 9.5,
        y: 66,
        title: 'Taş Ocak',
        category: 'atmosphere',
        icon: '🍲',
        summary: 'Kazanlarda baharatlı biranın kaynadığı dev ocak.',
        description:
          'Ocağın ateşi hiç sönmüyor. Soğuktan donan yolcular önce buraya gelip ellerini ısıtıyor.',
      },
      {
        id: 'ale_barrels',
        x: 26,
        y: 43,
        title: 'Bira Fıçıları',
        category: 'clue',
        icon: '🛢️',
        summary: 'Tezgâhın arkasına istiflenmiş meşe fıçılar.',
        description:
          'Fıçılardan biri diğerlerinden hafif ve sesi boş geliyor. Hanı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'gallery',
        x: 52.5,
        y: 27,
        title: 'Üst Kattaki Odalar',
        category: 'atmosphere',
        icon: '🛏️',
        summary: 'Yolcuların kaldığı odalara açılan ahşap galeri.',
        description:
          'Fırtına geçidi kapattığından beri odaların hepsi dolu. Kimin hangi odada kaldığını yalnızca Torstein biliyor.',
      },
      {
        id: 'drinkers',
        x: 62.5,
        y: 66,
        title: 'Kürklü Yolcular',
        category: 'atmosphere',
        icon: '🍺',
        summary: 'Uzun masalarda içip fısıldaşan kalabalık.',
        description:
          'Masalardakilerin çoğu fırtınada mahsur kalmış tüccar ve avcılar. Yabancıları görünce sesleri kısılıyor.',
      },
      {
        id: 'staircase',
        x: 65.5,
        y: 45,
        title: 'Üst Kata Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Galeriye çıkan dik ahşap merdiven.',
        description:
          'Basamakların üzerinde erimiş kar izleri var; biri dışarıdan gelip doğrudan yukarı çıkmış.',
      },
      {
        id: 'front_door',
        x: 94,
        y: 54,
        title: 'Açık Kalan Kapı',
        category: 'atmosphere',
        icon: '❄️',
        summary: 'Karın içeri savrulduğu ağır ahşap kapı.',
        description:
          'Kapı rüzgârdan sık sık açılıyor. Dışarıda avluya düşen kar, gelip gidenlerin izlerini çabucak örtüyor.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🍁 Kutsal Ağaç (Kahin Valda)',
    name: 'Kutsal Yürek Ağacı',
    subtitle: 'Dikili Taşlar Halkası — Kadim Tanrıların Koruluğu',
    scenarioType: 'winter',
    npcId: 'church',
    npcName: 'Kahin Valda',
    backgroundImage: '/backgrounds/interior_winter_church.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'valda',
        x: 18,
        y: 66,
        title: 'Kahin Valda (Taşların Yanı)',
        category: 'npc',
        icon: '🍁',
        summary: 'Elinde kemik tılsımlarla diz çökmüş, kukuletalı yaşlı kadın.',
        description:
          'Valda soğuk, kehanet dolu fısıltılarla konuşuyor. Dünyevi suçlara kadim tanrıların gözünden bakıyor ve ağacın yapraklarında işaretler okuduğunu söylüyor.',
        actionText: 'Kahin Valda ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'sacred_tree',
        x: 57.5,
        y: 30,
        title: 'Kutsal Ağaç',
        category: 'atmosphere',
        icon: '🌳',
        summary: 'Kemik beyazı gövdesine rünler oyulmuş, kızıl yapraklı dev ağaç.',
        description:
          'Rünlerin bazıları çok eski, bazıları yeni oyulmuş. Kızıl yapraklar karın üzerine kan damlası gibi dökülüyor.',
      },
      {
        id: 'offerings',
        x: 61.5,
        y: 63,
        title: 'Köklerdeki Adaklar',
        category: 'clue',
        icon: '🕯️',
        summary: 'Mumlar, kemikler ve küçük adaklar.',
        description:
          'Adakların arasında buraya ait olmayan bir şey parlıyor. Koruluğu aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'frozen_pond',
        x: 55,
        y: 83,
        title: 'Donmuş Gölet',
        category: 'atmosphere',
        icon: '🧊',
        summary: 'Ağacın önündeki kara buzla kaplı gölet.',
        description:
          'Buzun bir köşesi yakın zamanda kırılmış ve yeniden donmuş. İnce buzun altında karanlık su görünüyor.',
      },
      {
        id: 'standing_stones',
        x: 35,
        y: 51,
        title: 'Dikili Taşlar',
        category: 'atmosphere',
        icon: '🪨',
        summary: 'Koruluğu çevreleyen, üzeri işaretli taşlar.',
        description:
          'Taşlardaki işaretleri artık Valda’dan başka kimse okuyamıyor. Halkanın içine silahla girmek yasak.',
      },
      {
        id: 'keep_path',
        x: 85,
        y: 39,
        title: 'Kaleye Dönen Yol',
        category: 'passage',
        icon: '🏰',
        summary: 'Meşalelerle aydınlanan, kale binalarına giden patika.',
        description:
          'Patikadaki ayak izleri karla dolmaya başlamış. Gece koruluğa gelen biri buradan geçmiş olmalı.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🏰 Gözcü Kalesi (Komutan Bjorn)',
    name: 'Gözcü Kalesi',
    subtitle: 'Frosthold Kalesinin Büyük Salonu — Demir Disiplin ve Kurt Postları',
    scenarioType: 'winter',
    npcId: 'graveyard',
    npcName: 'Komutan Bjorn',
    backgroundImage: '/backgrounds/interior_winter_graveyard.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    hotspots: [
      {
        id: 'bjorn',
        x: 64.5,
        y: 53,
        title: 'Komutan Bjorn (Savaş Masası)',
        category: 'npc',
        icon: '🏰',
        summary: 'Zincir zırhının üstüne kurt postu atmış, yüzü yara izli komutan.',
        description:
          'Bjorn nöbetçiler arasında demir bir disiplin sürdürüyor. Her yabancıya sızma ihtimali olan biri gibi bakıyor ve zayıflığa da yalana da tahammül etmiyor.',
        actionText: 'Komutan Bjorn ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'war_table',
        x: 75,
        y: 83,
        title: 'Savaş Masası',
        category: 'clue',
        icon: '🗺️',
        summary: 'Oyma bir harita ve üzerinde dizili ahşap figürler.',
        description:
          'Figürlerden biri gecenin nöbet düzeninden farklı bir yere konmuş. Kaleyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'high_seat',
        x: 33,
        y: 42,
        title: 'Yüksek Koltuk',
        category: 'atmosphere',
        icon: '🪑',
        summary: 'Kürsünün üstünde, postlarla örtülü ahşap taht.',
        description:
          'Kalenin sahibi bu koltukta oturup hüküm verir. Komutan, kalenin efendisi yokken buraya oturmuyor.',
      },
      {
        id: 'feast_tables',
        x: 26,
        y: 61,
        title: 'Ziyafet Masaları',
        category: 'atmosphere',
        icon: '🍖',
        summary: 'Üstünde boş kâseler ve boynuz kadehler kalmış uzun masalar.',
        description:
          'Akşam yemeği aceleyle bitirilmiş. Masalardan biri devrilip yeniden kurulmuş gibi duruyor.',
      },
      {
        id: 'weapon_racks',
        x: 4.5,
        y: 51,
        title: 'Silah Rafları',
        category: 'atmosphere',
        icon: '🪓',
        summary: 'Baltalar, mızraklar ve yuvarlak kalkanlar.',
        description:
          'Silahların sayımı her sabah yapılıyor. Raftaki bir baltanın yerinde boşluk var.',
      },
      {
        id: 'iron_door',
        x: 92.5,
        y: 52,
        title: 'Demir Kaplı Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'İki nöbetçinin beklediği ağır kapı.',
        description:
          'Kapı surlara ve kalenin alt katlarına açılıyor. Nöbetçiler kimin geçtiğini tek tek deftere yazıyor.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⛏️ Maden (Madenci Durn)',
    name: 'Terk Edilmiş Maden',
    subtitle: 'Eski Demir Madeni — Buz Sarkıtları ve Karanlık Tüneller',
    scenarioType: 'winter',
    npcId: 'mill',
    npcName: 'Madenci Durn',
    backgroundImage: '/backgrounds/interior_winter_mill.webp',
    particleType: 'dust',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'durn',
        x: 22.5,
        y: 53,
        title: 'Madenci Durn (Fener)',
        category: 'npc',
        icon: '⛏️',
        summary: 'Elinde fener ve kazmayla omzunun üstünden bakan yaşlı madenci.',
        description:
          'Durn kaba ve kısa konuşuyor. Klanından olmayan kimseye güvenmiyor ve tünelleri herkesten iyi biliyor.',
        actionText: 'Madenci Durn ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'ore_carts',
        x: 46.5,
        y: 65,
        title: 'Cevher Arabaları',
        category: 'atmosphere',
        icon: '🛒',
        summary: 'Paslı raylar üzerinde cevherle dolu arabalar.',
        description:
          'Maden terk edilmiş sayılıyor ama arabalardaki cevher yeni çıkarılmış gibi duruyor.',
      },
      {
        id: 'pickaxes',
        x: 40,
        y: 45,
        title: 'Duvardaki Kazmalar',
        category: 'atmosphere',
        icon: '⛏️',
        summary: 'Çivilere asılmış kazmalar ve fenerler.',
        description:
          'Kazmalardan birinin sapı buz tutmamış; yakın zamanda kullanılmış.',
      },
      {
        id: 'mine_entrance',
        x: 63,
        y: 50,
        title: 'Maden Girişi',
        category: 'passage',
        icon: '🌨️',
        summary: 'Tünelin sonunda soluk mavi bir ışık.',
        description:
          'Giriş dağın yamacına, geçide yakın bir noktaya açılıyor. Maden, kaleye fark edilmeden gelmenin bir yolu olabilir.',
      },
      {
        id: 'blocked_tunnel',
        x: 82.5,
        y: 59,
        title: 'Göçmüş Yan Tünel',
        category: 'clue',
        icon: '🪨',
        summary: 'Kayalar ve kırık kirişlerle yarı kapanmış bir tünel.',
        description:
          'Kayaların arasında insan geçecek kadar bir aralık açılmış. Madeni aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'crates',
        x: 91,
        y: 77,
        title: 'Sandıklar',
        category: 'atmosphere',
        icon: '📦',
        summary: 'Tünel ağzına istiflenmiş ahşap sandıklar.',
        description:
          'Sandıkların üzerinde maden mührü yok. Ne taşıdıkları belli değil.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🛡️ Sur (Einar)',
    name: 'Sur Kapısı',
    subtitle: 'Buz Surunun Nöbet Odası — Donmuş Geçidin Bekçisi',
    scenarioType: 'winter',
    npcId: 'farm',
    npcName: 'Einar',
    backgroundImage: '/backgrounds/interior_winter_farm.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'einar',
        x: 37,
        y: 66,
        title: 'Einar (Kapı Kemeri)',
        category: 'npc',
        icon: '🛡️',
        summary: 'Yayını tutup geçidi izleyen genç nöbetçi.',
        description:
          'Einar dondurucu rüzgâra rağmen yerinden ayrılmıyor. Geçitteki her hareketi görüyor ve suru geçmek isteyen herkese şüpheyle bakıyor.',
        actionText: 'Einar ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'fireplace',
        x: 9,
        y: 71,
        title: 'Nöbet Ocağı',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Nöbetçilerin ısındığı küçük taş ocak.',
        description:
          'Ocağın yanındaki odunlar azalmış. Gece nöbetinde burada kaç kişinin ısındığı belli değil.',
      },
      {
        id: 'bow_rack',
        x: 23.5,
        y: 53,
        title: 'Yaylar ve Sadaklar',
        category: 'atmosphere',
        icon: '🏹',
        summary: 'Duvara asılmış uzun yaylar.',
        description:
          'Sadaklardan birindeki okların sayısı eksik. Nöbetçiler her oku tek tek sayar.',
      },
      {
        id: 'frozen_pass',
        x: 54,
        y: 53,
        title: 'Donmuş Geçit',
        category: 'atmosphere',
        icon: '🏔️',
        summary: 'Kemerin ardında uzanan buz duvarlı dağ geçidi.',
        description:
          'Fırtınadan beri geçitten kimse gelmedi; en azından nöbet defterine göre.',
      },
      {
        id: 'gate_winch',
        x: 71.5,
        y: 73,
        title: 'Kapı Makarası',
        category: 'clue',
        icon: '⛓️',
        summary: 'Ağır kapıyı açan zincirli makara.',
        description:
          'Zincirdeki buz kırılmış; kapı gece açılıp kapanmış olmalı. Suru aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'battlement_stairs',
        x: 90,
        y: 53,
        title: 'Surlara Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Mazgallara tırmanan dar ahşap merdiven.',
        description:
          'Merdivenin tepesinden bütün geçit ve kalenin avlusu görünüyor.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '⚔️ İnfaz Meydanı (Muhafız Kenneth)',
    name: 'İnfaz Meydanı',
    subtitle: 'Askerî Yargı Avlusu — Darağacı, Kafesler ve Soğuk Adalet',
    scenarioType: 'winter',
    npcId: 'clinic',
    npcName: 'Muhafız Kenneth',
    backgroundImage: '/backgrounds/interior_winter_clinic.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'kenneth',
        x: 85,
        y: 47,
        title: 'Muhafız Kenneth (Yargı Kürsüsü)',
        category: 'npc',
        icon: '⚔️',
        summary: 'Eldivenli elini kürsüye dayamış, soğuk bakışlı muhafız.',
        description:
          'Kenneth garnizonu isyandan koruyan tek şeyin korku olduğuna inanıyor. Suçu acımasız bir kesinlikle ölçüyor.',
        actionText: 'Muhafız Kenneth ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'ledger',
        x: 57.5,
        y: 81,
        title: 'Yargı Defteri',
        category: 'clue',
        icon: '📖',
        summary: 'Kürsüdeki kalın, deri ciltli defter ve kum saati.',
        description:
          'Defterin son sayfalarından biri koparılmış. İnfaz meydanını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'gallows',
        x: 30,
        y: 41,
        title: 'Darağacı',
        category: 'atmosphere',
        icon: '🪢',
        summary: 'Boş bir ilmeğin sallandığı ahşap darağacı.',
        description:
          'İlmek yeni bağlanmış. Garnizonda yakında bir infaz yapılacağı fısıldanıyor.',
      },
      {
        id: 'cages',
        x: 57.5,
        y: 54,
        title: 'Demir Kafesler',
        category: 'atmosphere',
        icon: '⛓️',
        summary: 'Avluda asılı duran boş kafesler.',
        description:
          'Kafeslerden birinin kilidi açık bırakılmış. İçindeki kar ezilmiş.',
      },
      {
        id: 'bonfire',
        x: 49,
        y: 61,
        title: 'Avludaki Ateş',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Nöbetçilerin etrafında beklediği büyük ateş.',
        description:
          'Ateşin külleri arasında yanmamış bir kumaş parçası var.',
      },
      {
        id: 'dungeon_door',
        x: 14.5,
        y: 53,
        title: 'Zindan Kapısı',
        category: 'passage',
        icon: '🚪',
        summary: 'Kulenin dibindeki demir parmaklıklı kapı.',
        description:
          'Kapının ardındaki merdiven zindana iniyor. Mahkûmlar sorguya buradan çıkarılıyor.',
      },
    ],
  },
};

// Millfield, Kentucky (1994): küçük kasaba, sonbahar, Twin Peaks havası
const MODERN_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '⭐ Karakol (Şerif Dale Cooper)',
    name: 'Millfield Şerif Karakolu',
    subtitle: 'Karakol — Kasabanın Sırlarını Saklayan Masa',
    scenarioType: 'modern',
    npcId: 'tavern',
    npcName: 'Şerif Dale Cooper',
    backgroundImage: '/backgrounds/interior_modern_tavern.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    hotspots: [
      {
        id: 'sheriff',
        x: 88,
        y: 48,
        title: 'Şerif Dale Cooper',
        category: 'npc',
        icon: '⭐',
        summary: 'Elinde kahvesiyle pencereden dışarı bakan sakin şerif.',
        description:
          'Cooper kasabayı yıllardır tanır ve skandaldan korur. Sorularına nazikçe cevap verir ama Millfield\'in adını lekeleyecek bir şeyi kolay kolay söylemez.',
        actionText: 'Şerif ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'case_board',
        x: 17.5,
        y: 34,
        title: 'Soruşturma Panosu',
        category: 'atmosphere',
        icon: '📌',
        summary: 'Fotoğrafların ve kırmızı ipliklerin kasaba haritasına bağlandığı mantar pano.',
        description:
          'İplerin hepsi haritanın ortasında birleşiyor. Bazı fotoğrafların yeri boş; biri onları panodan sökmüş.',
      },
      {
        id: 'radio_console',
        x: 45.5,
        y: 46,
        title: 'Telsiz Masası',
        category: 'atmosphere',
        icon: '📻',
        summary: 'Yeşil ekranları yanıp sönen eski telsiz konsolu.',
        description:
          'Gece boyunca gelen çağrılar burada kayda geçiyor. Hat çoğu gece sessiz.',
      },
      {
        id: 'gun_rack',
        x: 57.5,
        y: 39,
        title: 'Kilitli Silah Dolabı',
        category: 'atmosphere',
        icon: '🔒',
        summary: 'Camın ardında sıralanmış av tüfekleri.',
        description: 'Dolabın anahtarı yalnızca şerifte. Tüfeklerin hepsi yerinde görünüyor.',
      },
      {
        id: 'holding_cell',
        x: 69.5,
        y: 37,
        title: 'Nezarethane',
        category: 'passage',
        icon: '🚪',
        summary: 'Demir parmaklıklı tek kişilik hücre.',
        description: 'Hücre bu hafta boş. Ranzanın üzerindeki battaniye yine de yeni katlanmış gibi.',
      },
      {
        id: 'case_files',
        x: 62,
        y: 68,
        title: 'Dava Dosyaları',
        category: 'clue',
        icon: '🗂️',
        summary: 'Masanın üzerinde üst üste yığılmış sarı dosyalar.',
        description:
          'Dosyaların arasında aceleyle kapatılmış eski bir vaka var. Karakolu aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'cherry_pie',
        x: 65,
        y: 86,
        title: 'Yarım Kalmış Vişneli Turta',
        category: 'atmosphere',
        icon: '🥧',
        summary: 'Lokantadan gelmiş, yarısı yenmiş bir dilim turta.',
        description: 'Şerif her sabah lokantaya uğrar. Kasabada olan biteni de çoğunlukla orada duyar.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🛎️ Hotel (Gerald)',
    name: 'Millfield Hotel',
    subtitle: 'Otel Lobisi — Arka Merdivenleri Kimse Kullanmaz',
    scenarioType: 'modern',
    npcId: 'church',
    npcName: 'Gerald',
    backgroundImage: '/backgrounds/interior_modern_church.webp',
    particleType: 'dust',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'gerald',
        x: 21,
        y: 49,
        title: 'Gerald (Resepsiyon)',
        category: 'npc',
        icon: '🛎️',
        summary: 'Yeleği ve papyonuyla resepsiyonda bekleyen otel müdürü.',
        description:
          'Gerald misafirlerine karşı hep naziktir ve kimin hangi saatte merdivenden çıktığını bilir. Ama otelin itibarı onun için her şeyden önce gelir.',
        actionText: 'Gerald ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'key_rack',
        x: 7.5,
        y: 34,
        title: 'Anahtar Dolabı',
        category: 'clue',
        icon: '🔑',
        summary: 'Oda numaralı kancalar; birkaç anahtar eksik.',
        description:
          'Kancaların bazıları boş ama defterde o odalar boş görünüyor. Oteli aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'guest_ledger',
        x: 36,
        y: 71,
        title: 'Misafir Defteri',
        category: 'atmosphere',
        icon: '📖',
        summary: 'Tezgâhta açık duran giriş-çıkış defteri.',
        description: 'Son sayfadaki bir satır karalanmış. Gerald defterin her zaman düzgün tutulduğunu söylüyor.',
      },
      {
        id: 'static_tv',
        x: 38,
        y: 28,
        title: 'Karıncalı Televizyon',
        category: 'atmosphere',
        icon: '📺',
        summary: 'Köşedeki tüplü televizyonda yalnızca parazit var.',
        description: 'Kanal saatlerdir çekmiyor. Kimse kapatmaya da zahmet etmemiş.',
      },
      {
        id: 'grandfather_clock',
        x: 46.5,
        y: 26,
        title: 'Duvar Saati',
        category: 'atmosphere',
        icon: '🕰️',
        summary: 'Sarkacı ağır ağır sallanan eski duvar saati.',
        description: 'Saat birkaç dakika geri kalıyor. Misafirler buna güvenip yanlış saat söylemiş olabilir.',
      },
      {
        id: 'staircase',
        x: 57,
        y: 45,
        title: 'Üst Katlara Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Loş koridorlara çıkan dar ahşap merdiven.',
        description: 'Basamaklar her adımda gıcırdıyor. Gece biri yukarı çıksa resepsiyondan duyulur.',
      },
      {
        id: 'service_door',
        x: 68.5,
        y: 45,
        title: 'Aralık Kalmış Servis Kapısı',
        category: 'passage',
        icon: '🚪',
        summary: 'Arka sokağa açılan servis kapısı.',
        description: 'Kapının önünde yere düşmüş kâğıtlar var. Buradan girip çıkan resepsiyonun önünden geçmek zorunda değil.',
      },
      {
        id: 'lace_windows',
        x: 88,
        y: 37,
        title: 'Dantel Perdeli Pencereler',
        category: 'atmosphere',
        icon: '🌙',
        summary: 'Alacakaranlığın soğuk mavi ışığının süzüldüğü pencereler.',
        description: 'Pencereler ana caddeye bakıyor. Lobiden geçen herkes dışarıdan da görülebilir.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🕹️ Video Oyuncusu (Randy)',
    name: 'Pixel Arcade',
    subtitle: 'Video Oyun Salonu — Neon Işığında Dedikodular',
    scenarioType: 'modern',
    npcId: 'graveyard',
    npcName: 'Randy Kowalski',
    backgroundImage: '/backgrounds/interior_modern_graveyard.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    hotspots: [
      {
        id: 'randy',
        x: 79.5,
        y: 60,
        title: 'Randy Kowalski',
        category: 'npc',
        icon: '🕹️',
        summary: 'Bir makineye yaslanıp sırıtan geveze salon sahibi.',
        description:
          'Randy herkesle konuşur, film ve oyunlardan bahsetmeyi sever. Sorular ciddileşince konuyu ustalıkla başka yere çeker.',
        actionText: 'Randy ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'prize_counter',
        x: 9,
        y: 45,
        title: 'Ödül Vitrini',
        category: 'atmosphere',
        icon: '🧸',
        summary: 'Peluş oyuncaklar ve şeker kavanozlarıyla dolu vitrin.',
        description: 'Ödüllerin çoğu yıllardır kimse tarafından alınmamış. Vitrin camında yeni parmak izleri var.',
      },
      {
        id: 'token_machine',
        x: 24,
        y: 60,
        title: 'Jeton Makinesi',
        category: 'atmosphere',
        icon: '🪙',
        summary: 'Paraları jetona çeviren metal makine.',
        description: 'Makinenin kasası her akşam boşaltılıyor. Randy o geceki hasılatın eksik çıktığından yakınıyor.',
      },
      {
        id: 'regulars',
        x: 34.5,
        y: 56,
        title: 'Salonun Müdavimleri',
        category: 'atmosphere',
        icon: '🎮',
        summary: 'Makinelerin başında toplanmış kasabalı gençler.',
        description: 'Gençler her akşam burada. Kimin geç saate kadar kaldığını onlardan iyi kimse bilmez.',
      },
      {
        id: 'back_room',
        x: 43.5,
        y: 37,
        title: 'Boncuk Perdeli Arka Oda',
        category: 'clue',
        icon: '🚪',
        summary: 'Salonun en dibindeki depoya açılan kapı.',
        description:
          'Randy bu kapıdan müşterileri hiç geçirmiyor. Salonu aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'trash_can',
        x: 60,
        y: 77,
        title: 'Taşan Çöp Kutusu',
        category: 'atmosphere',
        icon: '🥤',
        summary: 'Gazoz kutuları ve karton bardaklarla dolmuş çöp kutusu.',
        description: 'Çöp kutusu günlerdir boşaltılmamış. Salonun o gece ne kadar kalabalık olduğu buradan belli.',
      },
      {
        id: 'posters',
        x: 74.5,
        y: 13,
        title: 'Duvardaki Afişler',
        category: 'atmosphere',
        icon: '🖼️',
        summary: 'Soluk renkli film ve oyun afişleri.',
        description: 'Afişlerden birinin köşesi yırtılmış; arkasındaki duvarda bir telefon numarası yazılı.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '🥧 Lokanta (Donna)',
    name: 'The Maple Cafe & Diner',
    subtitle: 'Lokanta — Kasabanın Bütün Dedikoduları Bu Tezgâhta',
    scenarioType: 'modern',
    npcId: 'mill',
    npcName: 'Donna Perkins',
    backgroundImage: '/backgrounds/interior_modern_mill.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    hotspots: [
      {
        id: 'donna',
        x: 33.5,
        y: 55,
        title: 'Donna Perkins',
        category: 'npc',
        icon: '☕',
        summary: 'Elindeki kahve potuyla tedirgin bakan güler yüzlü garson.',
        description:
          'Donna müşterilerinin hepsini adıyla tanır ve herkesin kahvesini nasıl içtiğini bilir. Bugün gözü sürekli pencerede.',
        actionText: 'Donna ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'pie_case',
        x: 12.5,
        y: 80,
        title: 'Turta Vitrini',
        category: 'atmosphere',
        icon: '🥧',
        summary: 'Vişneli ve elmalı turtaların dizildiği cam vitrin.',
        description: 'Lokantanın meşhur vişneli turtası. Şerif her sabah bir dilimini karakola götürür.',
      },
      {
        id: 'order_tickets',
        x: 14.5,
        y: 36,
        title: 'Sipariş Fişleri',
        category: 'clue',
        icon: '🧾',
        summary: 'Mutfak penceresindeki askıda sallanan fişler.',
        description:
          'Fişlerde saat yazıyor; kimin ne zaman burada olduğunu gösterebilirler. Lokantayı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'payphone',
        x: 51.5,
        y: 40,
        title: 'Ankesörlü Telefon',
        category: 'atmosphere',
        icon: '☎️',
        summary: 'Tuvaletlere giden koridordaki duvar telefonu.',
        description: 'Kasabada evden aramak istemeyenler buraya gelir. Donna o gece birinin uzun uzun konuştuğunu hatırlıyor.',
      },
      {
        id: 'back_hall',
        x: 58,
        y: 38,
        title: 'Arka Koridor',
        category: 'passage',
        icon: '🚪',
        summary: 'Tuvaletlere ve arka kapıya açılan koridor.',
        description: 'Koridorun sonundaki kapı otoparka çıkıyor. Ön kapıyı kullanmadan girip çıkmak mümkün.',
      },
      {
        id: 'booths',
        x: 69.5,
        y: 62,
        title: 'Kırmızı Localar',
        category: 'atmosphere',
        icon: '🍔',
        summary: 'Menülerin arkasından fısıldaşan kasabalılar.',
        description: 'Locadakiler yabancıyı görünce konuşmayı kesiyor. Kasabada haberler buradan yayılıyor.',
      },
      {
        id: 'street_window',
        x: 82,
        y: 37,
        title: 'Sokağa Bakan Camlar',
        category: 'atmosphere',
        icon: '🍂',
        summary: 'Yaprakların döküldüğü Maple Caddesi.',
        description: 'Camlardan karakol ve petrol istasyonu görülüyor. Gelip geçen her araba buradan fark edilir.',
      },
      {
        id: 'jukebox',
        x: 94.5,
        y: 74,
        title: 'Müzik Kutusu',
        category: 'atmosphere',
        icon: '🎵',
        summary: 'Rengârenk ışıklarıyla eski şarkılar çalan müzik kutusu.',
        description: 'Aynı şarkı bütün gün tekrar tekrar çalıyor. Onu kimin seçtiğini kimse söylemiyor.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '⛽ Petrol İstasyonu (Earl)',
    name: 'Yol Kenarı Petrol İstasyonu',
    subtitle: 'Petrol İstasyonu — Kasabaya Giren Her Araba Buradan Geçer',
    scenarioType: 'modern',
    npcId: 'farm',
    npcName: 'Earl Hutchins',
    backgroundImage: '/backgrounds/interior_modern_farm.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    hotspots: [
      {
        id: 'earl',
        x: 86,
        y: 60,
        title: 'Earl Hutchins',
        category: 'npc',
        icon: '🔧',
        summary: 'Ellerini bezle silen, yağa bulanmış tulumlu pompacı.',
        description:
          'Earl az konuşur ama her plakayı hatırlar. Kasabaya kim girdi kim çıktı, en iyi o bilir.',
        actionText: 'Earl ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'fuel_pumps',
        x: 11.5,
        y: 57,
        title: 'Akaryakıt Pompaları',
        category: 'atmosphere',
        icon: '⛽',
        summary: 'Camın ardında, gün batımında turuncuya kesmiş eski pompalar.',
        description: 'Pompalardan biri o gece geç saatte kullanılmış. Sayaç hâlâ son satışı gösteriyor.',
      },
      {
        id: 'parked_truck',
        x: 27,
        y: 49,
        title: 'Park Etmiş Kamyonet',
        category: 'atmosphere',
        icon: '🛻',
        summary: 'Dükkânın önünde bekleyen tozlu, kahverengi kamyonet.',
        description: 'Kamyonet sabahtan beri orada. Sahibinin kim olduğunu Earl söylemek istemiyor gibi.',
      },
      {
        id: 'payphone',
        x: 39,
        y: 50,
        title: 'Ankesörlü Telefon',
        category: 'atmosphere',
        icon: '☎️',
        summary: 'Kapının yanında duvara monte, eskimiş telefon.',
        description: 'Yol üstündeki tek telefon bu. Gece yarısı birinin buradan aradığını Earl hatırlıyor.',
      },
      {
        id: 'news_tv',
        x: 54.5,
        y: 58,
        title: 'Haber Bülteni',
        category: 'atmosphere',
        icon: '📺',
        summary: 'Köşedeki küçük televizyonda yerel haberler.',
        description: 'Spiker cinayetten henüz bahsetmiyor. Kasabada haberin yayılması bir gün sürüyor.',
      },
      {
        id: 'plate_log',
        x: 63,
        y: 80,
        title: 'Plaka Defteri',
        category: 'clue',
        icon: '📋',
        summary: 'Tezgâhtaki panoda tutulan araç kayıtları.',
        description:
          'Earl yakıt alan araçların plakalarını not eder. İstasyonu aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'cash_register',
        x: 67,
        y: 62,
        title: 'Yazar Kasa',
        category: 'atmosphere',
        icon: '💵',
        summary: 'Tuşları aşınmış eski yazar kasa.',
        description: 'Kasa fişleri gün sonunda kutuya atılıyor. Earl hesap tutmayı pek sevmiyor.',
      },
      {
        id: 'storeroom',
        x: 78.5,
        y: 45,
        title: 'Arka Depo',
        category: 'passage',
        icon: '🚪',
        summary: 'Tezgâhın arkasında aralık duran dar kapı.',
        description: 'Kapı yağ tenekeleri ve yedek parçaların durduğu küçük depoya açılıyor. Earl oraya kimseyi sokmuyor.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🍺 Bar (David)',
    name: "David's Bar",
    subtitle: 'Bar — Fısıltıların Duman Arasında Kaybolduğu Yer',
    scenarioType: 'modern',
    npcId: 'clinic',
    npcName: 'David',
    backgroundImage: '/backgrounds/interior_modern_clinic.webp',
    particleType: 'fog',
    lightingTone: 'dim-amber',
    hotspots: [
      {
        id: 'david',
        x: 18.5,
        y: 49,
        title: 'David (Tezgâh)',
        category: 'npc',
        icon: '🍺',
        summary: 'Sessizce bardak kurulayan sakallı barmen.',
        description:
          'David çok konuşmaz ama tezgâhta fısıldanan her şeyi duyar. Müşterilerinin sırrını tutmasıyla bilinir.',
        actionText: 'David ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'ashtray',
        x: 28.5,
        y: 73,
        title: 'Tüten Kül Tablası',
        category: 'atmosphere',
        icon: '🚬',
        summary: 'Tezgâhta hâlâ dumanı tüten bir sigara.',
        description: 'Sigarayı bırakan kişi az önce çıkmış olmalı. David kim olduğunu söylemeye pek hevesli değil.',
      },
      {
        id: 'wall_phone',
        x: 29.5,
        y: 45,
        title: 'Duvar Telefonu',
        category: 'atmosphere',
        icon: '☎️',
        summary: 'Kasanın yanındaki kablolu telefon.',
        description: 'Barın müdavimleri buradan taksi çağırır. Yanındaki takvimde bir gün daire içine alınmış.',
      },
      {
        id: 'old_tv',
        x: 49,
        y: 28,
        title: 'Rafın Üstündeki Televizyon',
        category: 'atmosphere',
        icon: '📺',
        summary: 'Sesi kısılmış tüplü televizyon.',
        description: 'Gece yarısından sonra yalnızca parazit veriyor. Müşteriler saati ona bakarak tahmin ediyor.',
      },
      {
        id: 'storage_room',
        x: 58,
        y: 46,
        title: 'Arka Depo',
        category: 'clue',
        icon: '🚪',
        summary: 'Kapısı aralık bırakılmış depo odası.',
        description:
          'Rafların arasında bara ait olmayan bir şey göze çarpıyor. Barı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'pool_table',
        x: 67,
        y: 57,
        title: 'Bilardo Masası',
        category: 'atmosphere',
        icon: '🎱',
        summary: 'Yeşil lambanın altında yarım kalmış bir oyun.',
        description: 'Toplar oyunun ortasında bırakılmış. Oyuncular aceleyle çıkıp gitmiş gibi.',
      },
      {
        id: 'notice_board',
        x: 86,
        y: 39,
        title: 'Not Panosu',
        category: 'atmosphere',
        icon: '📝',
        summary: 'Sarı notlar ve fotoğraflarla dolu pano.',
        description: 'Notların çoğu iş ilanı ve kayıp kedi duyurusu. Birinde yalnızca bir saat ve bir oda numarası yazıyor.',
      },
    ],
  },
};

// İç mekânı hazırlanmış evrenler. Listede olmayan evrende iç mekân sayfası "henüz hazır değil" der.
const INTERIORS_BY_SCENARIO: Record<string, Record<string, LocationInteriorData>> = {
  medieval: MEDIEVAL_INTERIORS,
  cyberpunk: CYBERPUNK_INTERIORS,
  china: CHINA_INTERIORS,
  winter: WINTER_INTERIORS,
  modern: MODERN_INTERIORS,
};

export function getInterior(scenarioType: string, locationId: string): LocationInteriorData | null {
  return INTERIORS_BY_SCENARIO[scenarioType]?.[locationId] ?? null;
}

export function getScenarioInteriors(scenarioType: string): LocationInteriorData[] {
  return Object.values(INTERIORS_BY_SCENARIO[scenarioType] ?? {});
}
