export interface InteriorHotspot {
  id: string;
  x: number; // Yüzde olarak yatay konum (0 - 100)
  y: number; // Yüzde olarak dikey konum (0 - 100)
  title: string;
  category: 'npc' | 'clue' | 'atmosphere' | 'passage';
  icon: string;
  summary: string;
  description: string;
  clueSnippet?: string;
  actionText?: string;
  actionHref?: string;
}

export interface LocationInteriorData {
  id: string;
  // Mekân seçim menüsünde görünen kısa ad
  menuLabel: string;
  name: string;
  subtitle: string;
  scenarioType: string;
  npcId?: string;
  npcName?: string;
  backgroundImage: string;
  particleType: 'embers' | 'dust' | 'fog' | 'rain' | 'snow';
  // neon: meşale yerine pembe-camgöbeği titreyen neon ışığı (cyberpunk)
  lightingTone: 'warm-fire' | 'cold-moon' | 'dim-amber' | 'eerie-green' | 'neon';
  initialPan?: number; // Başlangıç kamera açısı (geriye dönük uyumluluk için tutuluyor)
  hotspots: InteriorHotspot[];
}

// İç mekânlar evrene göre ayrılır: aynı mekân id'si (ör. tavern) her evrende başka bir yerdir
const MEDIEVAL_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🍺 Taverna (Kardeş Aldric)',
    name: 'Ashenmoor Tavernası',
    subtitle: 'Karga ve Kadeh — Sırların ve Fısıltıların Sığınağı',
    scenarioType: 'medieval',
    npcId: 'tavern',
    npcName: 'Kardeş Aldric',
    backgroundImage: '/backgrounds/interior_tavern_panorama.jpg',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: -15,
    hotspots: [
      {
        id: 'aldric',
        x: 21,
        y: 52,
        title: 'Kardeş Aldric (Hancı)',
        category: 'npc',
        icon: '🍺',
        summary: 'Tezgâhın arkasında gergin bir şekilde kupa dolduran hancı.',
        description:
          'Kardeş Aldric, elleri hafifçe titreyerek müşterilerine bira dolduruyor. Bakışları sürekli kapıya ve şöminenin karanlık köşelerine kayıyor. Köydeki son olaylar hakkında bildiklerini saklamakta zorlanıyor gibi.',
        actionText: 'Aldric ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'fireplace',
        x: 88,
        y: 62,
        title: 'Büyük Taş Şömine ve Fısıldaşanlar',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Ateşin sıcaklığına sığınmış kapüşonlu köylüler.',
        description:
          'Közlerin çıtırtısı arasında fısıltılar duyuluyor: "...dün gece mezarlık tarafında parlayan meşaleler vardı... Silas yine kilisenin çanını çalmadı..." Köylüler Engizitörün gölgesini görünce aniden susuyor.',
        clueSnippet: 'Dün gece mezarlıkta meşaleler görüldüğüne dair kulak misafiri olunan bir fısıltı.',
      },
      {
        id: 'barrels',
        x: 8,
        y: 68,
        title: 'Meşe Bira Varilleri ve Gizli Bölme',
        category: 'clue',
        icon: '🛢️',
        summary: 'Tezgâhın arkasına istiflenmiş eski meşe fıçılar.',
        description:
          'En alttaki fıçının üzerinde kilise mührüne benzeyen kazınmış bir işaret var. Varillerin arkasındaki zeminde taze tebeşir tozu ve kül kalıntıları dikkat çekiyor.',
        clueSnippet: 'Hancının tezgâhının dibindeki fıçıda gizli bir işaret ve zemin kalıntıları bulundu.',
      },
      {
        id: 'stairs',
        x: 52,
        y: 42,
        title: 'Gıcırdayan Üst Kat Merdivenleri',
        category: 'passage',
        icon: '🪜',
        summary: 'Karanlık kiralık odalara çıkan ahşap merdiven.',
        description:
          'Yukarıdan ağır ayak sesleri ve tahta gıcırtıları geliyor. Hancının dediğine göre üst kattaki köşe oda iki gündür kilitli tutuluyor.',
      },
      {
        id: 'table',
        x: 63,
        y: 58,
        title: 'Gizli Müzakere Masası',
        category: 'clue',
        icon: '📜',
        summary: 'Yarım bırakılmış yemek ve mum damlalarıyla kaplı parşömen.',
        description:
          'Masada devrilmiş bir kalay kupa ve üzerinde kırmızı balmumu damlamış yırtık bir kâğıt parçası duruyor. Birisi Engizitör içeri girdiğinde aceleyle masayı terk etmiş.',
        clueSnippet: 'Masada aceleyle terk edilmiş, üzerinde kilise balmumu olan şüpheli bir not kırıntısı.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '⛪ Kilise (Peder Malachar)',
    name: 'Ashenmoor Kilisesi',
    subtitle: 'Aziz Jude Bazilikası — Taş Sütunlar ve Soğuk Dualar',
    scenarioType: 'medieval',
    npcId: 'church',
    npcName: 'Peder Malachar',
    backgroundImage: '/backgrounds/interior_church_panorama.jpg',
    particleType: 'dust',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'malachar',
        x: 26,
        y: 54,
        title: 'Peder Malachar (Kürsü)',
        category: 'npc',
        icon: '⛪',
        summary: 'Kürsünün yanında dua kitabını inceleyen din adamı.',
        description:
          'Peder Malachar soğuk gözlerle seni süzüyor. Tavırları son derece hesaplı ve eğitimli bir zekâyı ele veriyor. Kilisenin kutsal emanetlerini ve köyün günahlarını herkesten iyi bildiği aşikâr.',
        actionText: 'Malachar ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'altar',
        x: 50,
        y: 55,
        title: 'Kutsal Sunak ve Vitray Pencere',
        category: 'clue',
        icon: '🕯️',
        summary: 'Ayin masası ve tepedeki görkemli gül vitray.',
        description:
          'Gül pencereden süzülen solgun ay ışığı sunağın üzerindeki gümüş kadehi aydınlatıyor. Kadehin kenarında kurumuş koyu renkli bir leke var; şaraptan çok daha kıvamlı görünüyor.',
        clueSnippet: 'Sunaktaki gümüş kadehte kanı andıran kurumuş bir sıvı kalıntısı.',
      },
      {
        id: 'tapestry',
        x: 78,
        y: 45,
        title: 'Eski Kilise Duvar Halısı',
        category: 'atmosphere',
        icon: '🖼️',
        summary: 'Yüz yıllık dini dokuma ve gizli duvar çatlağı.',
        description:
          'Halının arkasında hafif bir hava akımı hissediliyor. Taş duvarda kriptaya veya yeraltı mahzenine giden gizli bir geçit olabilir.',
      },
      {
        id: 'candelabra',
        x: 93,
        y: 58,
        title: 'Devasa Döküm Şamdan',
        category: 'atmosphere',
        icon: '🕯️',
        summary: 'Onlarca eriyen balmumu mumuyla aydınlanan köşe.',
        description:
          'Balmumunun ağır kokusu kilisenin rutubetli taş kokusuna karışıyor. Şamdanın kaidesine kazınmış tuhaf bir Latince mısra göze çarpıyor.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⚙️ Değirmen (Giles)',
    name: 'Ashenmoor Değirmeni',
    subtitle: 'Eski Un Değirmeni — Gıcırdayan Çarklar ve Beyaz Tozlar',
    scenarioType: 'medieval',
    npcId: 'mill',
    npcName: 'Değirmenci Giles',
    backgroundImage: '/backgrounds/interior_mill_panorama.jpg',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    initialPan: 10,
    hotspots: [
      {
        id: 'giles',
        x: 76,
        y: 60,
        title: 'Değirmenci Giles (Çalışma Masası)',
        category: 'npc',
        icon: '⚙️',
        summary: 'Tartıların ve defterlerin başında bekleyen unlu adam.',
        description:
          'Giles, un tozlarına bulanmış önlüğüyle tartıların arkasında duruyor. Sürekli etrafına bakınarak köyün tahıl ambarlarındaki eksilmeleri ve gece teslimatlarını gizlemeye çalışıyor.',
        actionText: 'Giles ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'gears',
        x: 22,
        y: 40,
        title: 'Devasa Ahşap Değirmen Çarkları',
        category: 'atmosphere',
        icon: '⚙️',
        summary: 'Ağır ağır dönen ve inleyen ahşap dişli mekanizması.',
        description:
          'Devasa dişliler her dönüşünde ürkütücü bir gıcırtı çıkarıyor. Çarkların dişleri arasında sıkışmış koyu renkli bir kumaş parçası var.',
        clueSnippet: 'Değirmen dişlisine takılmış yırtık, pelerin kumaşına benzer bir parça.',
      },
      {
        id: 'marked_sacks',
        x: 84,
        y: 78,
        title: 'Mühürlü Çuvallar',
        category: 'clue',
        icon: '🌾',
        summary: 'Üzerine kırmızı simgeler çizilmiş tahıl çuvalları.',
        description:
          'Bu çuvalların üzerindeki işaretler standart değirmen mührü değil. Okült bir ritüele ait koruma rünlerine benziyor. İçlerinde tahıldan başka ne saklanıyor olabilir?',
        clueSnippet: 'Çuvalların üzerine kırmızı boyayla çizilmiş esrarengiz pagan rünleri.',
      },
      {
        id: 'loft_stairs',
        x: 62,
        y: 46,
        title: 'Tavan Arası Merdiveni',
        category: 'passage',
        icon: '🪜',
        summary: 'Karanlık tahıl deposuna çıkan dik basamaklar.',
        description:
          'Basamaklarda taze ayak izleri ve un saçılmış. Biri yakın zamanda yukarıya bir şeyler taşımış.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🪦 Mezarlık (İhtiyar Silas)',
    name: 'Ashenmoor Mezarlığı',
    subtitle: 'Sisli Kabirler — Sessizliğin ve Toprağın Şahitliği',
    scenarioType: 'medieval',
    npcId: 'graveyard',
    npcName: 'İhtiyar Silas',
    backgroundImage: '/backgrounds/interior_graveyard_panorama.png',
    particleType: 'fog',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'silas',
        x: 48,
        y: 62,
        title: 'İhtiyar Silas (Mezarcı Kulübesi Yanı)',
        category: 'npc',
        icon: '🪦',
        summary: 'Küreğine yaslanmış, toprağı izleyen yaşlı mezarcı.',
        description:
          'Silas, kırk yıldır bu köyde ölen herkesi gömdü. Konuşurken gözlerini yerden ayırmıyor; ölülerin fısıltılarını canlıların yalanlarına tercih ettiğini söylüyor.',
        actionText: 'Silas ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'mausoleum',
        x: 65,
        y: 38,
        title: 'Eski Aile Anıt Mezarı',
        category: 'clue',
        icon: '🏛️',
        summary: 'Kapısı aralık kalmış antik taş türbe.',
        description:
          'Türbenin demir kapısındaki kilit zorlanarak kırılmış. İçeriden taze yakılmış mum kokusu geliyor. Biri mezarları kazmadan önce burada ayin yapmış olmalı.',
        clueSnippet: 'Anıt mezarın kilidi kırılmış ve içeride yeni yakılmış balmumu kalıntıları bulundu.',
      },
      {
        id: 'open_grave',
        x: 35,
        y: 65,
        title: 'Yeni Kazılmış İsimsiz Kabir',
        category: 'clue',
        icon: '⛏️',
        summary: 'Henüz doldurulmamış çamurlu mezar çukuru.',
        description:
          'Çukurun kenarında bir kadın eldiveni ve kırılmış bir haç kolye ucu çamura batmış vaziyette yatıyor.',
        clueSnippet: 'Yeni kazılmış mezarın kenarında bulunan çamura batmış haç kolye ucu.',
      },
    ],
  },
};

// Neon Prime (cyberpunk). "Aranabilecek yer" noktaları sabit bir ipucu vermez: oyuncuyu mekânın
// aramasına yönlendirir, bulunan ipucu o vaka için üretilmiş gerçek ipucudur.
const CYBERPUNK_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🚔 Karakol (Kael Voss)',
    name: 'Neon Prime Karakolu',
    subtitle: 'Nöbetçi Masası — Arama İzinlerinin ve Bitmeyen Raporların Yeri',
    scenarioType: 'cyberpunk',
    npcId: 'tavern',
    npcName: 'Kael Voss',
    backgroundImage: '/backgrounds/interior_cyberpunk_tavern.webp',
    particleType: 'rain',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'kael',
        x: 33,
        y: 57,
        title: 'Memur Kael Voss (Nöbetçi Masası)',
        category: 'npc',
        icon: '👮',
        summary: 'Holografik dosyaların başında yorgun gözlerle bekleyen memur.',
        description:
          'Kael Voss, gözündeki implantın soluk ışığında ekrandaki dosyaları kaydırıyor. Her isteği masasına ne kadar iş açacağına göre tartıyor. Arama izinleri onun imzasından geçiyor.',
        actionText: 'Kael Voss ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'wanted_board',
        x: 9,
        y: 38,
        title: 'Aranan Afişleri ve Şehir Haritası',
        category: 'atmosphere',
        icon: '📌',
        summary: 'Solmuş afişler, işaretli bir harita ve üst üste yapıştırılmış notlar.',
        description:
          'Mantar panoda solmuş aranan afişleri, raptiyelerle işaretlenmiş bir şehir haritası ve üst üste yapıştırılmış notlar var. Bazı dosyalar çoktan kapanmış ama kimse afişleri indirmeye zahmet etmemiş.',
      },
      {
        id: 'holding_cell',
        x: 51,
        y: 52,
        title: 'Nezarethane',
        category: 'atmosphere',
        icon: '🔒',
        summary: 'Soluk camgöbeği ışık altında parmaklıkların ardındaki gözaltılar.',
        description:
          'Parmaklıkların ardında gözaltılar bekliyor. Kapının önündeki iki memur alçak sesle konuşuyor; içeriden biri dışarıdakilere bir şey fısıldamaya çalışıyor.',
      },
      {
        id: 'evidence_lockers',
        x: 64,
        y: 55,
        title: 'Delil Dolapları',
        category: 'clue',
        icon: '🗄️',
        summary: 'Sıra sıra dizilmiş numaralı metal dolaplar.',
        description:
          'Numaralı metal dolapların birkaçının kilidi zorlanmış gibi duruyor. Karakolun burasını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'street_window',
        x: 85,
        y: 47,
        title: 'Yağmurlu Cadde',
        category: 'atmosphere',
        icon: '🌃',
        summary: 'Camın ardında neon tabelalar ve seyyar yemek tezgâhları.',
        description:
          'Neon tabelalar, seyyar yemek tezgâhları ve alçaktan uçan bir dron. Şehir, karakolun içinde olanlardan habersiz akıp gidiyor.',
      },
      {
        id: 'printer',
        x: 26,
        y: 88,
        title: 'Eski Yazıcı',
        category: 'atmosphere',
        icon: '🖨️',
        summary: 'Hâlâ kâğıtla çalışan, son çıktısı yarım kalmış bir yazıcı.',
        description:
          'Karakol yeni sistemlere geçmeyi yıllardır erteliyor. Yazıcının ağzında yarım kalmış bir rapor sallanıyor.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🍜 Lokanta (Mirel Sato)',
    name: 'Static Spoon',
    subtitle: 'Gece Boyu Açık Erişte Lokantası — Kuryelerin, Polislerin ve Uykusuzların Durağı',
    scenarioType: 'cyberpunk',
    npcId: 'church',
    npcName: 'Mirel Sato',
    backgroundImage: '/backgrounds/interior_cyberpunk_church.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'mirel',
        x: 18,
        y: 50,
        title: 'Mirel Sato (Tezgâh)',
        category: 'npc',
        icon: '🍜',
        summary: 'Buharın içinde kepçesiyle kazanların başında duran lokanta sahibi.',
        description:
          'Metal önkolu buharın içinde parlıyor. Kepçeyi kazana daldırırken gözü kapıdan girip çıkan herkeste. Bu tezgâhtan geçen her söz bir gün işine yarayabilir.',
        actionText: 'Mirel Sato ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'regulars',
        x: 44,
        y: 60,
        title: 'Tezgâhtaki Müdavimler',
        category: 'atmosphere',
        icon: '🥢',
        summary: 'Eriştelerine eğilmiş kuryeler ve gece vardiyasından çıkanlar.',
        description:
          'Konuşmalar alçak sesle yapılıyor ama yan yana oturanlar birbirinin her kelimesini duyuyor. Burada sır tutmak, erişteyi soğumadan bitirmekten zor.',
      },
      {
        id: 'kitchen_door',
        x: 53,
        y: 50,
        title: 'Mutfağa Açılan Arka Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'Aralık kapının ardında tavalar ve sokağa açılan servis çıkışı.',
        description:
          'Mutfağın arkasındaki servis çıkışı doğrudan ara sokağa açılıyor. Buradan girip çıkan birini tezgâhtakiler fark etmez.',
      },
      {
        id: 'vending_machine',
        x: 65,
        y: 44,
        title: 'Ezik Otomat',
        category: 'atmosphere',
        icon: '🥤',
        summary: 'Camı çatlamış, yarısı boş bir içecek otomatı.',
        description:
          'Biri yumruğunu camına geçirmiş; çatlak hâlâ duruyor. İçindeki içeceklerin yarısının son kullanma tarihi çoktan geçmiş.',
      },
      {
        id: 'back_booth',
        x: 85,
        y: 80,
        title: 'Arka Köşedeki Masa',
        category: 'clue',
        icon: '🍲',
        summary: 'Yarım bırakılmış bir kâse ve dağılmış yemek çubukları.',
        description:
          'Biri buradan aceleyle kalkmış. Lokantanın arka köşelerini aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'foggy_window',
        x: 86,
        y: 33,
        title: 'Buğulu Vitrin',
        category: 'atmosphere',
        icon: '🌧️',
        summary: 'Yağmur damlalarının arasından süzülen pembe neon.',
        description:
          'Buğulu camın ardında caddenin neon ışıkları bulanıklaşıyor. İçeriden dışarısı görünmüyor, dışarıdan da içerisi.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🏥 Klinik (Brakk Coil)',
    name: 'Neon Prime Kliniği',
    subtitle: 'Yeraltı Siber Cerrahisi — Faturasız Ameliyatlar, Sorusuz Hastalar',
    scenarioType: 'cyberpunk',
    npcId: 'graveyard',
    npcName: 'Brakk Coil',
    backgroundImage: '/backgrounds/interior_cyberpunk_graveyard.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'brakk',
        x: 70,
        y: 57,
        title: 'Brakk Coil (Çalışma Masası)',
        category: 'npc',
        icon: '🩺',
        summary: 'Masasında mekanik bir eli söken siber cerrah.',
        description:
          'Brakk, başını kaldırmadan konuşuyor; tornavidası mekanik elin eklemlerinde dolaşıyor. Burada her işlemin bir bedeli var ve Brakk kimseye güvenmiyor.',
        actionText: 'Brakk Coil ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'bio_storage',
        x: 21,
        y: 48,
        title: 'Biyolojik Saklama Dolapları',
        category: 'clue',
        icon: '🧪',
        summary: 'Buzlu camların ardında yeşil ışıkta parlayan şişeler.',
        description:
          'Etiketsiz tüpler ve şişeler raflara dizilmiş; bazı rafların yakın zamanda boşaltıldığı belli. Kliniği aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'surgery_chair',
        x: 56,
        y: 65,
        title: 'Ameliyat Koltuğu',
        category: 'atmosphere',
        icon: '💺',
        summary: 'Tavandan sarkan robotik kolların altındaki yıpranmış koltuk.',
        description:
          'Deri koltuk sayısız ameliyattan geçmiş. Zemindeki lekeler hiçbir zaman tam olarak temizlenmemiş.',
      },
      {
        id: 'plastic_curtain',
        x: 33,
        y: 45,
        title: 'Plastik Perdenin Ardı',
        category: 'passage',
        icon: '🚪',
        summary: 'Kutularla dolu bir arka odayı gizleyen yarı saydam perde.',
        description:
          'Perdenin ardındaki odada hastaların görmemesi gereken işler yapılıyor olmalı. İçeriden soğutucu uğultusu geliyor.',
      },
      {
        id: 'scrap_implants',
        x: 91,
        y: 86,
        title: 'Hurda İmplantlar',
        category: 'atmosphere',
        icon: '🦾',
        summary: 'Bir kasaya gelişigüzel atılmış sökülmüş robot kolları.',
        description:
          'Kullanılmış implantlar ve sökülmüş protezler üst üste yığılmış. Kimin bedeninden çıktıkları belli değil.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '🛠️ Tamirhane (AURA-9)',
    name: 'AURA Tamirhanesi',
    subtitle: 'Siber Protez ve Robot Atölyesi — Kıvılcımlar, Lehim ve Yedek Parçalar',
    scenarioType: 'cyberpunk',
    npcId: 'mill',
    npcName: 'AURA-9',
    backgroundImage: '/backgrounds/interior_cyberpunk_mill.webp',
    particleType: 'embers',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'aura',
        x: 37,
        y: 51,
        title: 'AURA-9 (Lehim Tezgâhı)',
        category: 'npc',
        icon: '🤖',
        summary: 'Bir devre kartını lehimleyen beyaz-krom kabuklu android.',
        description:
          'AURA-9’un mavi optik sensörleri her hareketi kaydediyor. Ses tonu kibar ve ticari, ama bakışları bir makineye göre fazlasıyla dikkatli.',
        actionText: 'AURA-9 ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'robot_arm',
        x: 17,
        y: 62,
        title: 'Robotik Montaj Kolu',
        category: 'atmosphere',
        icon: '🦿',
        summary: 'Masanın üzerinde kendi kendine çalışan montaj kolu.',
        description:
          'Kol, sahibine ihtiyaç duymadan vida sıkıyor. Atölyede kimse yokken de iş durmuyor.',
      },
      {
        id: 'limb_rack',
        x: 55,
        y: 42,
        title: 'Yedek Uzuv Rafı',
        category: 'atmosphere',
        icon: '🦾',
        summary: 'Kancalara asılı kollar ve raflarda dizili boş bakışlı yüzler.',
        description:
          'Bazı parçaların seri numaraları kazınarak silinmiş. Bu rafın kaçta kaçının yasal yoldan geldiğini kimse sormuyor.',
      },
      {
        id: 'circuit_table',
        x: 45,
        y: 88,
        title: 'Devre Kartı Masası',
        category: 'clue',
        icon: '💾',
        summary: 'Yarı sökülmüş kartlar ve hafıza modülleri.',
        description:
          'Masadaki hafıza modüllerinden birinin kayıtları silinmeye çalışılmış gibi. Atölyeyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'shutter',
        x: 82,
        y: 52,
        title: 'Yarı Açık Kepenk',
        category: 'passage',
        icon: '🚪',
        summary: 'Kepengin altından görünen yağmurlu sokak.',
        description:
          'Atölyeye gece yarısı da girip çıkılabiliyor. Kepengin önündeki ıslak zeminde silik ayak izleri var.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🏮 Sokak Pazarı (Ash)',
    name: 'Gece Pazarı',
    subtitle: 'Neon Prime Sokak Pazarı — Hurda Teknoloji, Sokak Yemeği ve Satılık Fısıltılar',
    scenarioType: 'cyberpunk',
    npcId: 'farm',
    npcName: 'Ash',
    backgroundImage: '/backgrounds/interior_cyberpunk_farm.webp',
    particleType: 'rain',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'ash',
        x: 21,
        y: 57,
        title: 'Ash (Hurda Tezgâhı)',
        category: 'npc',
        icon: '🧥',
        summary: 'Kapüşonunun altından kalabalığı izleyen sokak satıcısı.',
        description:
          'Gözlüğü alnında, eldivenli elleri kenetli. Bu pazarda görünmez olmak bir zırh; Ash de bu zırhın ardından her şeyi görüyor.',
        actionText: 'Ash ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'ash_stall',
        x: 35,
        y: 85,
        title: 'Ash’in Tezgâhı',
        category: 'clue',
        icon: '🔌',
        summary: 'Kablo yumakları, eski piller ve elden düşme devre kartları.',
        description:
          'Tezgâhtaki parçaların bazıları bir hurdaya göre fazla yeni duruyor. Tezgâhı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'wok_stall',
        x: 44,
        y: 59,
        title: 'Buharlı Wok Tezgâhı',
        category: 'atmosphere',
        icon: '🥘',
        summary: 'Devasa tavada erişte çeviren bir aşçı.',
        description:
          'Buhar neon ışıkla karışıyor; kızgın yağın sesi yakındaki konuşmaları bastırıyor.',
      },
      {
        id: 'lantern_alley',
        x: 65,
        y: 46,
        title: 'Fenerli Pazar Sokağı',
        category: 'passage',
        icon: '🏮',
        summary: 'Kâğıt fenerlerin altında ilerleyen şemsiyeli kalabalık.',
        description:
          'Bu kalabalığın içinde biri takip edilse kimse fark etmez. Sokak, şehrin daha karanlık katlarına doğru uzanıyor.',
      },
      {
        id: 'hanging_cables',
        x: 85,
        y: 40,
        title: 'Karşı Tezgâh',
        category: 'atmosphere',
        icon: '🧵',
        summary: 'Kancalardan sarkan kablolar ve tencereler.',
        description:
          'Satıcı müşterilerden çok sokağın başını izliyor. Polis geldiğinde bu tezgâhın ilk kapanan olacağı belli.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🍸 Bar (Vera Nyx)',
    name: 'Velvet Static',
    subtitle: 'Karartma Barı — Paralı Askerlerin, Aracıların ve Kaybolmak İsteyenlerin Mekânı',
    scenarioType: 'cyberpunk',
    npcId: 'clinic',
    npcName: 'Vera Nyx',
    backgroundImage: '/backgrounds/interior_cyberpunk_clinic.webp',
    particleType: 'dust',
    lightingTone: 'neon',
    initialPan: 0,
    hotspots: [
      {
        id: 'vera',
        x: 72,
        y: 48,
        title: 'Vera Nyx (Bar Tezgâhı)',
        category: 'npc',
        icon: '🍸',
        summary: 'Bir bardağı ağır ağır parlatırken salonu süzen barmen.',
        description:
          'Çene hattındaki implant neon ışıkta belli belirsiz parlıyor. Herkesle samimi konuşuyor ama kendisi hakkında hiçbir şey söylemiyor.',
        actionText: 'Vera Nyx ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'private_room',
        x: 28,
        y: 45,
        title: 'Boncuk Perdeli Özel Oda',
        category: 'passage',
        icon: '🚪',
        summary: 'Kırmızı ışıklı, alçak sesle pazarlık yapılan arka oda.',
        description:
          'Perdenin ardında birileri anlaşma yapıyor. Davetsiz girenlerin buradan nasıl çıktığını kimse hatırlamıyor.',
      },
      {
        id: 'stage',
        x: 50,
        y: 45,
        title: 'Sahne',
        category: 'atmosphere',
        icon: '🎸',
        summary: 'Sis makinesinin dumanında çalan bir grup.',
        description:
          'Müzik o kadar yüksek ki masalardaki fısıltılar kayboluyor. Burada konuşulanı ancak yan masadaki duyar.',
      },
      {
        id: 'side_booth',
        x: 9,
        y: 64,
        title: 'Yan Odadaki Masa',
        category: 'atmosphere',
        icon: '🤝',
        summary: 'Grafitili duvarın önünde pazarlık yapan iki kişi.',
        description:
          'Siber kollu iki kişi masaya eğilmiş, bir şeyin fiyatında anlaşmaya çalışıyor. Seni görünce sesleri kısılıyor.',
      },
      {
        id: 'behind_bar',
        x: 80,
        y: 72,
        title: 'Bar Tezgâhının Arkası',
        category: 'clue',
        icon: '🍾',
        summary: 'Işıklı raflar ve tezgâhın altındaki kilitli çekmeceler.',
        description:
          'Rafların arkasında içkiden fazlası saklanıyor olabilir. Barın arkasını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
    ],
  },
};

// Jinling (Çin hanedan dönemi). Cyberpunk'taki gibi "aranabilecek yer" noktaları sabit ipucu vermez,
// oyuncuyu mekânın aramasına yönlendirir.
const CHINA_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🍵 Çay Evi (Lin Feng)',
    name: 'Altın Lotus Çay Evi',
    subtitle: 'Çay Evi ve Han — Yolcuların, Tüccarların ve Fısıltıların Durağı',
    scenarioType: 'china',
    npcId: 'tavern',
    npcName: 'Lin Feng',
    backgroundImage: '/backgrounds/interior_china_tavern.webp',
    particleType: 'dust',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'lin_feng',
        x: 19,
        y: 49,
        title: 'Lin Feng (Çay Tezgâhı)',
        category: 'npc',
        icon: '🍵',
        summary: 'Demliği havada tutup çayı uzun bir yayla bardağa döken çay ustası.',
        description:
          'Lin Feng kibarca gülümsüyor ama gözleri her masada. Burada konuşulan her sözün bir değeri olduğunu ve o değeri kimin ödeyeceğini çok iyi biliyor.',
        actionText: 'Lin Feng ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'tea_counter',
        x: 30,
        y: 71,
        title: 'Çay Tezgâhı',
        category: 'atmosphere',
        icon: '🫖',
        summary: 'Demlikler, porselen fincanlar ve sıra sıra çay kavanozları.',
        description:
          'Kavanozların her birinde başka bir yörenin çayı var. En pahalıları, tezgâhın arkasında kilitli bir dolapta duruyor.',
      },
      {
        id: 'upper_gallery',
        x: 49,
        y: 27,
        title: 'Üst Kattaki Localar',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Perdeli, kafes paravanlı özel localar.',
        description:
          'Memurlar ve zengin tüccarlar üst katta, perdelerin ardında oturuyor. Aşağıdan bakan biri yalnızca gölgelerini görebilir.',
      },
      {
        id: 'guests',
        x: 60,
        y: 66,
        title: 'Fısıldaşan Müşteriler',
        category: 'atmosphere',
        icon: '🗣️',
        summary: 'Mangalın başında alçak sesle konuşan yolcular.',
        description:
          'Konuşmalar sen yaklaşınca kesiliyor. Masadakilerden biri fincanını bırakıp bakışlarını kapıya çeviriyor.',
      },
      {
        id: 'staircase',
        x: 75,
        y: 51,
        title: 'Üst Kata Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Oymalı tırabzanlı ahşap merdiven.',
        description:
          'Merdivenin basamakları gıcırdıyor; yukarı çıkan herkesi aşağıdakiler duyuyor. Han odaları koridorun sonunda.',
      },
      {
        id: 'back_room',
        x: 92,
        y: 55,
        title: 'Arka Odanın Kapısı',
        category: 'clue',
        icon: '🚪',
        summary: 'Avluya açılan, yarı aralık sürgülü kapı.',
        description:
          'Lin Feng özel misafirlerini bu kapıdan arka odaya alıyor. Çay evini aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🏯 Karargâh (Komutan Zhao)',
    name: 'İmparatorluk Garnizonu',
    subtitle: 'Muhafız Karargâhı — Silahların, Mühürlerin ve Emirlerin Salonu',
    scenarioType: 'china',
    npcId: 'church',
    npcName: 'Komutan Zhao',
    backgroundImage: '/backgrounds/interior_china_church.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'zhao',
        x: 84.5,
        y: 57,
        title: 'Komutan Zhao (Harita Masası)',
        category: 'npc',
        icon: '🏯',
        summary: 'Zırhının içinde dimdik duran, yüzü yara izli komutan.',
        description:
          'Zhao düzensizliğe ve ihanete tahammül etmiyor. Sert bir sesle konuşuyor ve her sorunun askerlerinin onurunu lekeleyip lekelemeyeceğini tartıyor.',
        actionText: 'Komutan Zhao ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'map_table',
        x: 57.5,
        y: 81,
        title: 'Savaş Haritası Masası',
        category: 'clue',
        icon: '🗺️',
        summary: 'Açılmış bir harita, balmumu mühürler ve fırça takımı.',
        description:
          'Haritanın üzerinde devriye yollarını gösteren işaretler var; bazıları yakın zamanda değiştirilmiş. Karargâhı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'weapon_racks',
        x: 11,
        y: 39,
        title: 'Silah Rafları',
        category: 'atmosphere',
        icon: '🔱',
        summary: 'Mızraklar, teberler ve kılıçlarla dolu raflar.',
        description:
          'Rafların her biri numaralı. Garnizonun silahları sayılı; eksik olan bir tanesi bile komutanın gözünden kaçmaz.',
      },
      {
        id: 'armor_stand',
        x: 26.5,
        y: 59,
        title: 'Zırh Askısı',
        category: 'atmosphere',
        icon: '🛡️',
        summary: 'Kırmızı tüylü miğferiyle boş bir pul zırh.',
        description:
          'Zırh, savaşta ölen eski bir komutana ait. Askerler önünden geçerken başlarını eğiyor.',
      },
      {
        id: 'barracks_door',
        x: 62.5,
        y: 53,
        title: 'Kışlaya Açılan Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'İki muhafızın beklediği ağır ahşap kapı.',
        description:
          'Kapının ardındaki koridor kışlaya ve zindana iniyor. Muhafızlar komutanın izni olmadan kimseyi geçirmiyor.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '⛩️ Tapınak (Keşiş Huikang)',
    name: 'Kadim Dağ Tapınağı',
    subtitle: 'Ata Ruhlarının Salonu — Tütsü, Mum ve Sessizlik',
    scenarioType: 'china',
    npcId: 'graveyard',
    npcName: 'Keşiş Huikang',
    backgroundImage: '/backgrounds/interior_china_graveyard.webp',
    particleType: 'dust',
    lightingTone: 'dim-amber',
    initialPan: 0,
    hotspots: [
      {
        id: 'huikang',
        x: 17.5,
        y: 66,
        title: 'Keşiş Huikang (Tütsü Kazanı)',
        category: 'npc',
        icon: '⛩️',
        summary: 'Tespihini çeken, gözleri yarı kapalı yaşlı keşiş.',
        description:
          'Huikang sakin bir sesle, bilmece gibi konuşuyor. İnsanların dünyevi hırslarının altındaki niyetleri sezdiğini söylüyor.',
        actionText: 'Keşiş Huikang ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'spirit_tablets',
        x: 43.5,
        y: 55,
        title: 'Ata Ruhu Tabletleri',
        category: 'clue',
        icon: '🕯️',
        summary: 'Mumlarla çevrili, sıra sıra dizilmiş ahşap tabletler.',
        description:
          'Tabletlerden birinin önündeki mumlar diğerlerinden yeni. Tapınağı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'statue',
        x: 42.5,
        y: 37,
        title: 'Altın Heykel',
        category: 'atmosphere',
        icon: '🪷',
        summary: 'Arka nişte oturan, yaldızı dökülmüş heykel.',
        description:
          'Heykelin önündeki tütsü dumanı hiç dağılmıyor. Köylüler burada verilen sözlerin bozulmadığına inanıyor.',
      },
      {
        id: 'incense_burner',
        x: 52,
        y: 71,
        title: 'Bronz Tütsü Kazanı',
        category: 'atmosphere',
        icon: '🌫️',
        summary: 'Salonun ortasında duman tüten büyük kazan.',
        description:
          'Kazandaki küller henüz soğumamış. Biri gece yarısı burada uzun süre dua etmiş olmalı.',
      },
      {
        id: 'courtyard_doors',
        x: 87.5,
        y: 51,
        title: 'Avluya Açılan Kafes Kapılar',
        category: 'passage',
        icon: '🚪',
        summary: 'Oymalı, kafesli büyük ahşap kapılar.',
        description:
          'Kapılar ay ışığındaki avluya ve oradan dağ yoluna açılıyor. Gece tapınağa girip çıkan biri buradan geçmek zorunda.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⚒️ Demirci (Usta Guan)',
    name: 'Usta Guan’ın Demirci Ocağı',
    subtitle: 'Silah Atölyesi — Kor, Çelik ve Çekiç Sesleri',
    scenarioType: 'china',
    npcId: 'mill',
    npcName: 'Usta Guan',
    backgroundImage: '/backgrounds/interior_china_mill.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'guan',
        x: 36,
        y: 50,
        title: 'Usta Guan (Örs)',
        category: 'npc',
        icon: '⚒️',
        summary: 'Kızgın bir bıçağı dövmek için çekicini kaldırmış iri yarı demirci.',
        description:
          'Guan’ın sesi çekicinden daha gür. Bu mahalledeki her silahı tanıyor ve kılıçlarının onursuz bir iş için kullanıldığı imasına öfkeleniyor.',
        actionText: 'Usta Guan ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'furnace',
        x: 16.5,
        y: 54,
        title: 'Taş Ocak',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Kor dolu, körükle beslenen taş ocak.',
        description:
          'Ocak gece gündüz yanıyor. Atölyede çalışan çırak, körüğün başından hiç ayrılmıyor.',
      },
      {
        id: 'blade_rack',
        x: 55,
        y: 39,
        title: 'Bitmiş Kılıçların Rafı',
        category: 'clue',
        icon: '🗡️',
        summary: 'Duvara dizilmiş kılıçlar ve bıçaklar.',
        description:
          'Raftaki kılıçların arasında bir boşluk var. Atölyeyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'quench_buckets',
        x: 52.5,
        y: 83,
        title: 'Su Kovaları',
        category: 'atmosphere',
        icon: '🪣',
        summary: 'Kızgın çeliğin soğutulduğu, buhar tüten kovalar.',
        description:
          'Kovaların dibinde demir talaşı birikmiş. Su sık sık değiştirilmiyor.',
      },
      {
        id: 'ingot_shelves',
        x: 70,
        y: 47,
        title: 'Külçe Rafları',
        category: 'atmosphere',
        icon: '🧱',
        summary: 'Üst üste dizilmiş demir külçeler.',
        description:
          'Külçelerin bir kısmı garnizonun mührünü taşıyor. Guan, ordu için de silah dövüyor.',
      },
      {
        id: 'workshop_door',
        x: 85,
        y: 47,
        title: 'Sokağa Açılan Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'Fenerle aydınlanan çift kanatlı ağır kapı.',
        description:
          'Kapının sürgüsü içeriden çekiliyor. Gece atölyeye girmek isteyen birinin Guan’ı uyandırması gerekir.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🎣 İskele (Mei Teyze)',
    name: 'Nehir İskelesi',
    subtitle: 'Balıkçı İskelesi — Ağlar, Kayıklar ve Sisli Sular',
    scenarioType: 'china',
    npcId: 'farm',
    npcName: 'Mei Teyze',
    backgroundImage: '/backgrounds/interior_china_farm.webp',
    particleType: 'fog',
    lightingTone: 'cold-moon',
    initialPan: 0,
    hotspots: [
      {
        id: 'mei',
        x: 23.5,
        y: 50,
        title: 'Mei Teyze (Ağ Başı)',
        category: 'npc',
        icon: '🎣',
        summary: 'Mangalın yanında ağ onaran yaşlı balıkçı kadın.',
        description:
          'Mei Teyze ağı onarırken yan gözle seni süzüyor. Nehir kıyısından geçen hiçbir şey gözünden kaçmaz, ama yabancılara saf görünmeyi iyi bilir.',
        actionText: 'Mei Teyze ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'fish_baskets',
        x: 40,
        y: 71,
        title: 'Balık Sepetleri',
        category: 'atmosphere',
        icon: '🐟',
        summary: 'Mangalın başında sıra sıra balık dolu sepetler.',
        description:
          'Sabah tutulan balıklar hâlâ satılmamış. Bugün pazara inen olmamış gibi.',
      },
      {
        id: 'nets',
        x: 27.5,
        y: 21,
        title: 'Kurumaya Asılmış Ağlar',
        category: 'atmosphere',
        icon: '🕸️',
        summary: 'Tavan kirişlerinden sarkan ıslak ağlar.',
        description:
          'Ağlardan biri yeni yırtılmış; düğümler aceleyle atılmış.',
      },
      {
        id: 'covered_pier',
        x: 57.5,
        y: 50,
        title: 'Üstü Kapalı İskele',
        category: 'passage',
        icon: '🌉',
        summary: 'Fenerlerle aydınlanan ahşap iskele yolu.',
        description:
          'İskele nehir boyunca mahallenin öbür ucuna uzanıyor. Gece buradan geçen birini sadece Mei Teyze görür.',
      },
      {
        id: 'moored_boats',
        x: 80,
        y: 66,
        title: 'Bağlı Kayıklar',
        category: 'clue',
        icon: '🛶',
        summary: 'İskeleye bağlanmış, halatları gevşek ahşap kayıklar.',
        description:
          'Kayıklardan birinin içi diğerlerinden ıslak; yakın zamanda kullanılmış. İskeleyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'far_pavilions',
        x: 87.5,
        y: 33,
        title: 'Karşı Kıyıdaki Köşkler',
        category: 'atmosphere',
        icon: '🏮',
        summary: 'Sisin ardında ışıkları yanan köşkler.',
        description:
          'Karşı kıyıda eğlence sürüyor. Nehrin sesi, oradaki müziği buraya kadar taşıyor.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '🌿 Şifacı (Bilgin Song)',
    name: 'Saray Eczanesi',
    subtitle: 'Şifacı ve Baharatçı — Kökler, Otlar ve Gizli Formüller',
    scenarioType: 'china',
    npcId: 'clinic',
    npcName: 'Bilgin Song',
    backgroundImage: '/backgrounds/interior_china_clinic.webp',
    particleType: 'dust',
    lightingTone: 'warm-fire',
    initialPan: 0,
    hotspots: [
      {
        id: 'song',
        x: 86,
        y: 55,
        title: 'Bilgin Song (Tezgâh)',
        category: 'npc',
        icon: '🌿',
        summary: 'Taş havanda ot döven, mavi cüppeli hekim.',
        description:
          'Song yumuşak ve ölçülü konuşuyor; duygulardan çok akla değer veriyor. İlaçlar kadar zehirleri de iyi tanıdığını gizlemiyor.',
        actionText: 'Bilgin Song ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'medicine_drawers',
        x: 43.5,
        y: 45,
        title: 'İlaç Çekmeceleri',
        category: 'clue',
        icon: '🗄️',
        summary: 'Duvarı baştan sona kaplayan yüzlerce küçük çekmece.',
        description:
          'Çekmecelerden birinin tozu silinmiş, kulpu parlıyor. Eczaneyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'back_room',
        x: 19,
        y: 61,
        title: 'Perdeli Arka Oda',
        category: 'passage',
        icon: '🚪',
        summary: 'Perdenin ardından sızan yeşil bir ışık.',
        description:
          'Arka odada bir şey kaynıyor. Song oraya müşterileri hiç almıyor.',
      },
      {
        id: 'acupuncture_model',
        x: 65.5,
        y: 53,
        title: 'Akupunktur Heykeli',
        category: 'atmosphere',
        icon: '🧍',
        summary: 'Vücudun noktalarını gösteren bronz insan figürü.',
        description:
          'Figürün boynundaki birkaç nokta, sık dokunulmaktan parlamış.',
      },
      {
        id: 'hanging_herbs',
        x: 35,
        y: 21,
        title: 'Asılı Kurutulmuş Otlar',
        category: 'atmosphere',
        icon: '🌾',
        summary: 'Tavandan sarkan kökler, otlar ve su kabakları.',
        description:
          'Otların bazıları buralarda yetişmiyor; uzak eyaletlerden getirilmiş, pahalı ve nadir.',
      },
    ],
  },
};

// Frosthold (kış). Açık hava sahnelerinde kar yağar; "aranabilecek yer" noktaları sabit ipucu vermez.
const WINTER_INTERIORS: Record<string, LocationInteriorData> = {
  tavern: {
    id: 'tavern',
    menuLabel: '🔥 Kış Hanı (Torstein)',
    name: 'Ocak Ateşi Hanı',
    subtitle: 'Kış Hanı — Fırtınadan Kaçanların Son Sığınağı',
    scenarioType: 'winter',
    npcId: 'tavern',
    npcName: 'Torstein',
    backgroundImage: '/backgrounds/interior_winter_tavern.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    hotspots: [
      {
        id: 'torstein',
        x: 33,
        y: 53,
        title: 'Torstein (Tezgâh)',
        category: 'npc',
        icon: '🔥',
        summary: 'Maşrapalara sıcak bira dolduran iri yarı, örgü sakallı hancı.',
        description:
          'Torstein müşterilerini kollar ve kimin fırtınadan önce geçidi aştığını bilir. Ocağın başında konuşulanları duyar ama duyduklarını kolay kolay anlatmaz.',
        actionText: 'Torstein ile Sorguya Başla',
        actionHref: '/interact/tavern',
      },
      {
        id: 'hearth',
        x: 9.5,
        y: 66,
        title: 'Taş Ocak',
        category: 'atmosphere',
        icon: '🍲',
        summary: 'Kazanlarda baharatlı biranın kaynadığı dev ocak.',
        description:
          'Ocağın ateşi hiç sönmüyor. Soğuktan donan yolcular önce buraya gelip ellerini ısıtıyor.',
      },
      {
        id: 'ale_barrels',
        x: 26,
        y: 43,
        title: 'Bira Fıçıları',
        category: 'clue',
        icon: '🛢️',
        summary: 'Tezgâhın arkasına istiflenmiş meşe fıçılar.',
        description:
          'Fıçılardan biri diğerlerinden hafif ve sesi boş geliyor. Hanı aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/tavern',
      },
      {
        id: 'gallery',
        x: 52.5,
        y: 27,
        title: 'Üst Kattaki Odalar',
        category: 'atmosphere',
        icon: '🛏️',
        summary: 'Yolcuların kaldığı odalara açılan ahşap galeri.',
        description:
          'Fırtına geçidi kapattığından beri odaların hepsi dolu. Kimin hangi odada kaldığını yalnızca Torstein biliyor.',
      },
      {
        id: 'drinkers',
        x: 62.5,
        y: 66,
        title: 'Kürklü Yolcular',
        category: 'atmosphere',
        icon: '🍺',
        summary: 'Uzun masalarda içip fısıldaşan kalabalık.',
        description:
          'Masalardakilerin çoğu fırtınada mahsur kalmış tüccar ve avcılar. Yabancıları görünce sesleri kısılıyor.',
      },
      {
        id: 'staircase',
        x: 65.5,
        y: 45,
        title: 'Üst Kata Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Galeriye çıkan dik ahşap merdiven.',
        description:
          'Basamakların üzerinde erimiş kar izleri var; biri dışarıdan gelip doğrudan yukarı çıkmış.',
      },
      {
        id: 'front_door',
        x: 94,
        y: 54,
        title: 'Açık Kalan Kapı',
        category: 'atmosphere',
        icon: '❄️',
        summary: 'Karın içeri savrulduğu ağır ahşap kapı.',
        description:
          'Kapı rüzgârdan sık sık açılıyor. Dışarıda avluya düşen kar, gelip gidenlerin izlerini çabucak örtüyor.',
      },
    ],
  },
  church: {
    id: 'church',
    menuLabel: '🍁 Kutsal Ağaç (Kahin Valda)',
    name: 'Kutsal Yürek Ağacı',
    subtitle: 'Dikili Taşlar Halkası — Kadim Tanrıların Koruluğu',
    scenarioType: 'winter',
    npcId: 'church',
    npcName: 'Kahin Valda',
    backgroundImage: '/backgrounds/interior_winter_church.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'valda',
        x: 18,
        y: 66,
        title: 'Kahin Valda (Taşların Yanı)',
        category: 'npc',
        icon: '🍁',
        summary: 'Elinde kemik tılsımlarla diz çökmüş, kukuletalı yaşlı kadın.',
        description:
          'Valda soğuk, kehanet dolu fısıltılarla konuşuyor. Dünyevi suçlara kadim tanrıların gözünden bakıyor ve ağacın yapraklarında işaretler okuduğunu söylüyor.',
        actionText: 'Kahin Valda ile Sorguya Başla',
        actionHref: '/interact/church',
      },
      {
        id: 'sacred_tree',
        x: 57.5,
        y: 30,
        title: 'Kutsal Ağaç',
        category: 'atmosphere',
        icon: '🌳',
        summary: 'Kemik beyazı gövdesine rünler oyulmuş, kızıl yapraklı dev ağaç.',
        description:
          'Rünlerin bazıları çok eski, bazıları yeni oyulmuş. Kızıl yapraklar karın üzerine kan damlası gibi dökülüyor.',
      },
      {
        id: 'offerings',
        x: 61.5,
        y: 63,
        title: 'Köklerdeki Adaklar',
        category: 'clue',
        icon: '🕯️',
        summary: 'Mumlar, kemikler ve küçük adaklar.',
        description:
          'Adakların arasında buraya ait olmayan bir şey parlıyor. Koruluğu aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/church',
      },
      {
        id: 'frozen_pond',
        x: 55,
        y: 83,
        title: 'Donmuş Gölet',
        category: 'atmosphere',
        icon: '🧊',
        summary: 'Ağacın önündeki kara buzla kaplı gölet.',
        description:
          'Buzun bir köşesi yakın zamanda kırılmış ve yeniden donmuş. İnce buzun altında karanlık su görünüyor.',
      },
      {
        id: 'standing_stones',
        x: 35,
        y: 51,
        title: 'Dikili Taşlar',
        category: 'atmosphere',
        icon: '🪨',
        summary: 'Koruluğu çevreleyen, üzeri işaretli taşlar.',
        description:
          'Taşlardaki işaretleri artık Valda’dan başka kimse okuyamıyor. Halkanın içine silahla girmek yasak.',
      },
      {
        id: 'keep_path',
        x: 85,
        y: 39,
        title: 'Kaleye Dönen Yol',
        category: 'passage',
        icon: '🏰',
        summary: 'Meşalelerle aydınlanan, kale binalarına giden patika.',
        description:
          'Patikadaki ayak izleri karla dolmaya başlamış. Gece koruluğa gelen biri buradan geçmiş olmalı.',
      },
    ],
  },
  graveyard: {
    id: 'graveyard',
    menuLabel: '🏰 Gözcü Kalesi (Komutan Bjorn)',
    name: 'Gözcü Kalesi',
    subtitle: 'Frosthold Kalesinin Büyük Salonu — Demir Disiplin ve Kurt Postları',
    scenarioType: 'winter',
    npcId: 'graveyard',
    npcName: 'Komutan Bjorn',
    backgroundImage: '/backgrounds/interior_winter_graveyard.webp',
    particleType: 'embers',
    lightingTone: 'warm-fire',
    hotspots: [
      {
        id: 'bjorn',
        x: 64.5,
        y: 53,
        title: 'Komutan Bjorn (Savaş Masası)',
        category: 'npc',
        icon: '🏰',
        summary: 'Zincir zırhının üstüne kurt postu atmış, yüzü yara izli komutan.',
        description:
          'Bjorn nöbetçiler arasında demir bir disiplin sürdürüyor. Her yabancıya sızma ihtimali olan biri gibi bakıyor ve zayıflığa da yalana da tahammül etmiyor.',
        actionText: 'Komutan Bjorn ile Sorguya Başla',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'war_table',
        x: 75,
        y: 83,
        title: 'Savaş Masası',
        category: 'clue',
        icon: '🗺️',
        summary: 'Oyma bir harita ve üzerinde dizili ahşap figürler.',
        description:
          'Figürlerden biri gecenin nöbet düzeninden farklı bir yere konmuş. Kaleyi aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/graveyard',
      },
      {
        id: 'high_seat',
        x: 33,
        y: 42,
        title: 'Yüksek Koltuk',
        category: 'atmosphere',
        icon: '🪑',
        summary: 'Kürsünün üstünde, postlarla örtülü ahşap taht.',
        description:
          'Kalenin sahibi bu koltukta oturup hüküm verir. Komutan, kalenin efendisi yokken buraya oturmuyor.',
      },
      {
        id: 'feast_tables',
        x: 26,
        y: 61,
        title: 'Ziyafet Masaları',
        category: 'atmosphere',
        icon: '🍖',
        summary: 'Üstünde boş kâseler ve boynuz kadehler kalmış uzun masalar.',
        description:
          'Akşam yemeği aceleyle bitirilmiş. Masalardan biri devrilip yeniden kurulmuş gibi duruyor.',
      },
      {
        id: 'weapon_racks',
        x: 4.5,
        y: 51,
        title: 'Silah Rafları',
        category: 'atmosphere',
        icon: '🪓',
        summary: 'Baltalar, mızraklar ve yuvarlak kalkanlar.',
        description:
          'Silahların sayımı her sabah yapılıyor. Raftaki bir baltanın yerinde boşluk var.',
      },
      {
        id: 'iron_door',
        x: 92.5,
        y: 52,
        title: 'Demir Kaplı Kapı',
        category: 'passage',
        icon: '🚪',
        summary: 'İki nöbetçinin beklediği ağır kapı.',
        description:
          'Kapı surlara ve kalenin alt katlarına açılıyor. Nöbetçiler kimin geçtiğini tek tek deftere yazıyor.',
      },
    ],
  },
  mill: {
    id: 'mill',
    menuLabel: '⛏️ Maden (Madenci Durn)',
    name: 'Terk Edilmiş Maden',
    subtitle: 'Eski Demir Madeni — Buz Sarkıtları ve Karanlık Tüneller',
    scenarioType: 'winter',
    npcId: 'mill',
    npcName: 'Madenci Durn',
    backgroundImage: '/backgrounds/interior_winter_mill.webp',
    particleType: 'dust',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'durn',
        x: 22.5,
        y: 53,
        title: 'Madenci Durn (Fener)',
        category: 'npc',
        icon: '⛏️',
        summary: 'Elinde fener ve kazmayla omzunun üstünden bakan yaşlı madenci.',
        description:
          'Durn kaba ve kısa konuşuyor. Klanından olmayan kimseye güvenmiyor ve tünelleri herkesten iyi biliyor.',
        actionText: 'Madenci Durn ile Sorguya Başla',
        actionHref: '/interact/mill',
      },
      {
        id: 'ore_carts',
        x: 46.5,
        y: 65,
        title: 'Cevher Arabaları',
        category: 'atmosphere',
        icon: '🛒',
        summary: 'Paslı raylar üzerinde cevherle dolu arabalar.',
        description:
          'Maden terk edilmiş sayılıyor ama arabalardaki cevher yeni çıkarılmış gibi duruyor.',
      },
      {
        id: 'pickaxes',
        x: 40,
        y: 45,
        title: 'Duvardaki Kazmalar',
        category: 'atmosphere',
        icon: '⛏️',
        summary: 'Çivilere asılmış kazmalar ve fenerler.',
        description:
          'Kazmalardan birinin sapı buz tutmamış; yakın zamanda kullanılmış.',
      },
      {
        id: 'mine_entrance',
        x: 63,
        y: 50,
        title: 'Maden Girişi',
        category: 'passage',
        icon: '🌨️',
        summary: 'Tünelin sonunda soluk mavi bir ışık.',
        description:
          'Giriş dağın yamacına, geçide yakın bir noktaya açılıyor. Maden, kaleye fark edilmeden gelmenin bir yolu olabilir.',
      },
      {
        id: 'blocked_tunnel',
        x: 82.5,
        y: 59,
        title: 'Göçmüş Yan Tünel',
        category: 'clue',
        icon: '🪨',
        summary: 'Kayalar ve kırık kirişlerle yarı kapanmış bir tünel.',
        description:
          'Kayaların arasında insan geçecek kadar bir aralık açılmış. Madeni aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/mill',
      },
      {
        id: 'crates',
        x: 91,
        y: 77,
        title: 'Sandıklar',
        category: 'atmosphere',
        icon: '📦',
        summary: 'Tünel ağzına istiflenmiş ahşap sandıklar.',
        description:
          'Sandıkların üzerinde maden mührü yok. Ne taşıdıkları belli değil.',
      },
    ],
  },
  farm: {
    id: 'farm',
    menuLabel: '🛡️ Sur (Einar)',
    name: 'Sur Kapısı',
    subtitle: 'Buz Surunun Nöbet Odası — Donmuş Geçidin Bekçisi',
    scenarioType: 'winter',
    npcId: 'farm',
    npcName: 'Einar',
    backgroundImage: '/backgrounds/interior_winter_farm.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'einar',
        x: 37,
        y: 66,
        title: 'Einar (Kapı Kemeri)',
        category: 'npc',
        icon: '🛡️',
        summary: 'Yayını tutup geçidi izleyen genç nöbetçi.',
        description:
          'Einar dondurucu rüzgâra rağmen yerinden ayrılmıyor. Geçitteki her hareketi görüyor ve suru geçmek isteyen herkese şüpheyle bakıyor.',
        actionText: 'Einar ile Sorguya Başla',
        actionHref: '/interact/farm',
      },
      {
        id: 'fireplace',
        x: 9,
        y: 71,
        title: 'Nöbet Ocağı',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Nöbetçilerin ısındığı küçük taş ocak.',
        description:
          'Ocağın yanındaki odunlar azalmış. Gece nöbetinde burada kaç kişinin ısındığı belli değil.',
      },
      {
        id: 'bow_rack',
        x: 23.5,
        y: 53,
        title: 'Yaylar ve Sadaklar',
        category: 'atmosphere',
        icon: '🏹',
        summary: 'Duvara asılmış uzun yaylar.',
        description:
          'Sadaklardan birindeki okların sayısı eksik. Nöbetçiler her oku tek tek sayar.',
      },
      {
        id: 'frozen_pass',
        x: 54,
        y: 53,
        title: 'Donmuş Geçit',
        category: 'atmosphere',
        icon: '🏔️',
        summary: 'Kemerin ardında uzanan buz duvarlı dağ geçidi.',
        description:
          'Fırtınadan beri geçitten kimse gelmedi; en azından nöbet defterine göre.',
      },
      {
        id: 'gate_winch',
        x: 71.5,
        y: 73,
        title: 'Kapı Makarası',
        category: 'clue',
        icon: '⛓️',
        summary: 'Ağır kapıyı açan zincirli makara.',
        description:
          'Zincirdeki buz kırılmış; kapı gece açılıp kapanmış olmalı. Suru aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/farm',
      },
      {
        id: 'battlement_stairs',
        x: 90,
        y: 53,
        title: 'Surlara Çıkan Merdiven',
        category: 'passage',
        icon: '🪜',
        summary: 'Mazgallara tırmanan dar ahşap merdiven.',
        description:
          'Merdivenin tepesinden bütün geçit ve kalenin avlusu görünüyor.',
      },
    ],
  },
  clinic: {
    id: 'clinic',
    menuLabel: '⚔️ İnfaz Meydanı (Muhafız Kenneth)',
    name: 'İnfaz Meydanı',
    subtitle: 'Askerî Yargı Avlusu — Darağacı, Kafesler ve Soğuk Adalet',
    scenarioType: 'winter',
    npcId: 'clinic',
    npcName: 'Muhafız Kenneth',
    backgroundImage: '/backgrounds/interior_winter_clinic.webp',
    particleType: 'snow',
    lightingTone: 'cold-moon',
    hotspots: [
      {
        id: 'kenneth',
        x: 85,
        y: 47,
        title: 'Muhafız Kenneth (Yargı Kürsüsü)',
        category: 'npc',
        icon: '⚔️',
        summary: 'Eldivenli elini kürsüye dayamış, soğuk bakışlı muhafız.',
        description:
          'Kenneth garnizonu isyandan koruyan tek şeyin korku olduğuna inanıyor. Suçu acımasız bir kesinlikle ölçüyor.',
        actionText: 'Muhafız Kenneth ile Sorguya Başla',
        actionHref: '/interact/clinic',
      },
      {
        id: 'ledger',
        x: 57.5,
        y: 81,
        title: 'Yargı Defteri',
        category: 'clue',
        icon: '📖',
        summary: 'Kürsüdeki kalın, deri ciltli defter ve kum saati.',
        description:
          'Defterin son sayfalarından biri koparılmış. İnfaz meydanını aramak için arama izni gerekir.',
        actionText: 'Burayı Araştır',
        actionHref: '/interact/clinic',
      },
      {
        id: 'gallows',
        x: 30,
        y: 41,
        title: 'Darağacı',
        category: 'atmosphere',
        icon: '🪢',
        summary: 'Boş bir ilmeğin sallandığı ahşap darağacı.',
        description:
          'İlmek yeni bağlanmış. Garnizonda yakında bir infaz yapılacağı fısıldanıyor.',
      },
      {
        id: 'cages',
        x: 57.5,
        y: 54,
        title: 'Demir Kafesler',
        category: 'atmosphere',
        icon: '⛓️',
        summary: 'Avluda asılı duran boş kafesler.',
        description:
          'Kafeslerden birinin kilidi açık bırakılmış. İçindeki kar ezilmiş.',
      },
      {
        id: 'bonfire',
        x: 49,
        y: 61,
        title: 'Avludaki Ateş',
        category: 'atmosphere',
        icon: '🔥',
        summary: 'Nöbetçilerin etrafında beklediği büyük ateş.',
        description:
          'Ateşin külleri arasında yanmamış bir kumaş parçası var.',
      },
      {
        id: 'dungeon_door',
        x: 14.5,
        y: 53,
        title: 'Zindan Kapısı',
        category: 'passage',
        icon: '🚪',
        summary: 'Kulenin dibindeki demir parmaklıklı kapı.',
        description:
          'Kapının ardındaki merdiven zindana iniyor. Mahkûmlar sorguya buradan çıkarılıyor.',
      },
    ],
  },
};

// İç mekânı hazırlanmış evrenler. Listede olmayan evrende iç mekân sayfası "henüz hazır değil" der.
const INTERIORS_BY_SCENARIO: Record<string, Record<string, LocationInteriorData>> = {
  medieval: MEDIEVAL_INTERIORS,
  cyberpunk: CYBERPUNK_INTERIORS,
  china: CHINA_INTERIORS,
  winter: WINTER_INTERIORS,
};

export function getInterior(scenarioType: string, locationId: string): LocationInteriorData | null {
  return INTERIORS_BY_SCENARIO[scenarioType]?.[locationId] ?? null;
}

export function getScenarioInteriors(scenarioType: string): LocationInteriorData[] {
  return Object.values(INTERIORS_BY_SCENARIO[scenarioType] ?? {});
}
